In [2]:
import pandas as pd

In [3]:
hardware_df = pd.read_csv("/Users/andrewweiland/UCCS_REU/quantum-optimizer-orchestration/brute_force_chains/cheap_optimizers/initial_test/hardware_aware/hardware_aware_test_results.csv")
optimize_df = pd.read_csv("/Users/andrewweiland/UCCS_REU/quantum-optimizer-orchestration/brute_force_chains/cheap_optimizers/initial_test/optimize_only/optimize_only_test_results.csv")

In [4]:
merged = pd.merge(hardware_df, optimize_df, on="opt_chain", suffixes=("_hardware", "_optimize"))

In [5]:
merged

,circuit_hardware,optimizer_hardware,artifact_path_hardware,opt_level_hardware,opt_1_hardware,opt_2_hardware,opt_3_hardware,opt_chain,runtime_hardware,final_depth_hardware,...,artifact_path_optimize,opt_level_optimize,opt_1_optimize,opt_2_optimize,opt_3_optimize,runtime_optimize,final_depth_optimize,final_two_qubit_gate_count_optimize,final_two_qubit_depth_optimize,final_total_gates_optimize
0,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,1,qiskit_ai,NaN,NaN,qft_8__qiskit_ai,1.002103,31,...,brute_force_chains/cheap_optimizers/initial_te...,1,qiskit_ai,NaN,NaN,0.843884,108,56,56,164
1,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,1,qiskit_standard,NaN,NaN,qft_8__qiskit_standard,0.020029,112,...,brute_force_chains/cheap_optimizers/initial_te...,1,qiskit_standard,NaN,NaN,0.012383,51,56,26,129
2,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,1,tket,NaN,NaN,qft_8__tket,1.145792,51,...,brute_force_chains/cheap_optimizers/initial_te...,1,tket,NaN,NaN,1.059701,51,56,26,129
3,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_ai,qiskit_ai,NaN,qft_8__qiskit_ai__qiskit_ai,0.418219,31,...,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_ai,qiskit_ai,NaN,0.471388,108,56,56,164
4,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_ai,qiskit_standard,NaN,qft_8__qiskit_ai__qiskit_standard,0.178461,100,...,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_ai,qiskit_standard,NaN,0.170455,101,56,56,129
5,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_ai,tket,NaN,qft_8__qiskit_ai__tket,1.393332,79,...,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_ai,tket,NaN,1.345175,108,56,56,129
6,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_standard,qiskit_ai,NaN,qft_8__qiskit_standard__qiskit_ai,0.269955,114,...,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_standard,qiskit_ai,NaN,0.124261,101,56,56,129
7,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_standard,qiskit_standard,NaN,qft_8__qiskit_standard__qiskit_standard,0.023073,111,...,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_standard,qiskit_standard,NaN,0.012297,51,56,26,129
8,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_standard,tket,NaN,qft_8__qiskit_standard__tket,1.203237,78,...,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_standard,tket,NaN,0.968230,51,56,26,129
9,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,tket,qiskit_ai,NaN,qft_8__tket__qiskit_ai,1.136095,80,...,brute_force_chains/cheap_optimizers/initial_te...,2,tket,qiskit_ai,NaN,1.221084,101,56,56,129
10,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,tket,qiskit_standard,NaN,qft_8__tket__qiskit_standard,0.941959,110,...,brute_force_chains/cheap_optimizers/initial_te...,2,tket,qiskit_standard,NaN,0.949602,51,56,26,129
11,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,tket,tket,NaN,qft_8__tket__tket,1.846858,51,...,brute_force_chains/cheap_optimizers/initial_te...,2,tket,tket,NaN,1.993882,51,56,26,129
12,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_ai,qiskit_ai,qft_8__qiskit_ai__qiskit_ai__qiskit_ai,0.433238,31,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_ai,qiskit_ai,0.386378,108,56,56,164
13,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_ai,qiskit_standard,qft_8__qiskit_ai__qiskit_ai__qiskit_standard,0.258436,114,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_ai,qiskit_standard,0.238175,101,56,56,129
14,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_ai,tket,qft_8__qiskit_ai__qiskit_ai__tket,1.313719,91,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_ai,tket,1.198725,108,56,56,129
15,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_standard,qiskit_ai,qft_8__qiskit_ai__qiskit_standard__qiskit_ai,0.392284,114,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_standard,qiskit_ai,0.247000,101,56,56,129
16,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_standard,qiskit_standard,qft_8__qiskit_ai__qiskit_standard__qiskit_stan...,0.144979,112,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_standard,qiskit_standard,0.126907,101,56,56,129
17,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_standard,tket,qft_8__qiskit_ai__qiskit_standard__tket,1.256950,89,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_standard,tket,1.093350,108,56,56,129
18,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,tket,qiskit_ai,qft_8__qiskit_ai__tket__qiskit_ai,1.431439,103,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,tket,qiskit_ai,1.255780,101,56,56,129
19,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,tket,qiskit_standard,qft_8__qiskit_ai__tket__qiskit_standard,1.285987,142,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,tket,qiskit_standard,1.066856,108,56,56,129
20,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,tket,tket,qft_8__qiskit_ai__tket__tket,2.150858,77,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,tket,tket,2.088341,108,56,56,129
21,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_ai,qiskit_ai,qft_8__qiskit_standard__qiskit_ai__qiskit_ai,0.496869,114,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_ai,qiskit_ai,0.231230,101,56,56,129
22,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_ai,qiskit_standard,qft_8__qiskit_standard__qiskit_ai__qiskit_stan...,0.329206,114,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_ai,qiskit_standard,0.118306,101,56,56,129
23,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_ai,tket,qft_8__qiskit_standard__qiskit_ai__tket,1.385695,78,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_ai,tket,1.186686,108,56,56,129
24,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_standard,qiskit_ai,qft_8__qiskit_standard__qiskit_standard__qiski...,0.260492,114,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_standard,qiskit_ai,0.140547,101,56,56,129
25,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_standard,qiskit_standard,qft_8__qiskit_standard__qiskit_standard__qiski...,0.025780,114,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_standard,qiskit_standard,0.021135,51,56,26,129
26,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_standard,tket,qft_8__qiskit_standard__qiskit_standard__tket,1.136532,80,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_standard,tket,0.983606,51,56,26,129
27,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,tket,qiskit_ai,qft_8__qiskit_standard__tket__qiskit_ai,1.516074,105,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,tket,qiskit_ai,1.189470,101,56,56,129
28,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,tket,qiskit_standard,qft_8__qiskit_standard__tket__qiskit_standard,1.194142,117,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,tket,qiskit_standard,0.952818,51,56,26,129
29,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,tket,tket,qft_8__qiskit_standard__tket__tket,2.070168,74,...,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,tket,tket,1.921506,51,56,26,129
30,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_ai,qiskit_ai,qft_8__tket__qiskit_ai__qiskit_ai,1.333139,83,...,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_ai,qiskit_ai,1.344650,101,56,56,129
31,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_ai,qiskit_standard,qft_8__tket__qiskit_ai__qiskit_standard,1.208829,112,...,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_ai,qiskit_standard,1.188238,101,56,56,129
32,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_ai,tket,qft_8__tket__qiskit_ai__tket,2.153197,77,...,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_ai,tket,2.066658,108,56,56,129
33,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_standard,qiskit_ai,qft_8__tket__qiskit_standard__qiskit_ai,1.113815,99,...,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_standard,qiskit_ai,1.043704,101,56,56,129
34,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_standard,qiskit_standard,qft_8__tket__qiskit_standard__qiskit_standard,0.928853,110,...,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_standard,qiskit_standard,0.952112,51,56,26,129
35,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_standard,tket,qft_8__tket__qiskit_standard__tket,1.983456,82,...,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_standard,tket,1.908197,51,56,26,129
36,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,tket,qiskit_ai,qft_8__tket__tket__qiskit_ai,2.042704,80,...,brute_force_chains/cheap_optimizers/initial_te...,3,tket,tket,qiskit_ai,1.970820,101,56,56,129
37,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,tket,qiskit_standard,qft_8__tket__tket__qiskit_standard,1.844736,111,...,brute_force_chains/cheap_optimizers/initial_te...,3,tket,tket,qiskit_standard,1.900990,51,56,26,129
38,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,tket,tket,qft_8__tket__tket__tket,2.732051,51,...,brute_force_chains/cheap_optimizers/initial_te...,3,tket,tket,tket,2.790288,51,56,26,129

In [7]:
merged["two_qubit_gate_difference"] =  merged["final_two_qubit_gate_count_hardware"] - merged["final_two_qubit_gate_count_optimize"]
merged["depth_difference"] = merged["final_depth_hardware"] - merged["final_depth_optimize"]
merged

,circuit_hardware,optimizer_hardware,artifact_path_hardware,opt_level_hardware,opt_1_hardware,opt_2_hardware,opt_3_hardware,opt_chain,runtime_hardware,final_depth_hardware,...,opt_1_optimize,opt_2_optimize,opt_3_optimize,runtime_optimize,final_depth_optimize,final_two_qubit_gate_count_optimize,final_two_qubit_depth_optimize,final_total_gates_optimize,two_qubit_gate_difference,depth_difference
0,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,1,qiskit_ai,NaN,NaN,qft_8__qiskit_ai,1.002103,31,...,qiskit_ai,NaN,NaN,0.843884,108,56,56,164,-4,-77
1,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,1,qiskit_standard,NaN,NaN,qft_8__qiskit_standard,0.020029,112,...,qiskit_standard,NaN,NaN,0.012383,51,56,26,129,52,61
2,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,1,tket,NaN,NaN,qft_8__tket,1.145792,51,...,tket,NaN,NaN,1.059701,51,56,26,129,0,0
3,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_ai,qiskit_ai,NaN,qft_8__qiskit_ai__qiskit_ai,0.418219,31,...,qiskit_ai,qiskit_ai,NaN,0.471388,108,56,56,164,-5,-77
4,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_ai,qiskit_standard,NaN,qft_8__qiskit_ai__qiskit_standard,0.178461,100,...,qiskit_ai,qiskit_standard,NaN,0.170455,101,56,56,129,45,-1
5,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_ai,tket,NaN,qft_8__qiskit_ai__tket,1.393332,79,...,qiskit_ai,tket,NaN,1.345175,108,56,56,129,0,-29
6,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_standard,qiskit_ai,NaN,qft_8__qiskit_standard__qiskit_ai,0.269955,114,...,qiskit_standard,qiskit_ai,NaN,0.124261,101,56,56,129,51,13
7,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_standard,qiskit_standard,NaN,qft_8__qiskit_standard__qiskit_standard,0.023073,111,...,qiskit_standard,qiskit_standard,NaN,0.012297,51,56,26,129,52,60
8,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_standard,tket,NaN,qft_8__qiskit_standard__tket,1.203237,78,...,qiskit_standard,tket,NaN,0.968230,51,56,26,129,0,27
9,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,tket,qiskit_ai,NaN,qft_8__tket__qiskit_ai,1.136095,80,...,tket,qiskit_ai,NaN,1.221084,101,56,56,129,24,-21
10,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,tket,qiskit_standard,NaN,qft_8__tket__qiskit_standard,0.941959,110,...,tket,qiskit_standard,NaN,0.949602,51,56,26,129,51,59
11,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,tket,tket,NaN,qft_8__tket__tket,1.846858,51,...,tket,tket,NaN,1.993882,51,56,26,129,0,0
12,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_ai,qiskit_ai,qft_8__qiskit_ai__qiskit_ai__qiskit_ai,0.433238,31,...,qiskit_ai,qiskit_ai,qiskit_ai,0.386378,108,56,56,164,-5,-77
13,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_ai,qiskit_standard,qft_8__qiskit_ai__qiskit_ai__qiskit_standard,0.258436,114,...,qiskit_ai,qiskit_ai,qiskit_standard,0.238175,101,56,56,129,51,13
14,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_ai,tket,qft_8__qiskit_ai__qiskit_ai__tket,1.313719,91,...,qiskit_ai,qiskit_ai,tket,1.198725,108,56,56,129,0,-17
15,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_standard,qiskit_ai,qft_8__qiskit_ai__qiskit_standard__qiskit_ai,0.392284,114,...,qiskit_ai,qiskit_standard,qiskit_ai,0.247000,101,56,56,129,51,13
16,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_standard,qiskit_standard,qft_8__qiskit_ai__qiskit_standard__qiskit_stan...,0.144979,112,...,qiskit_ai,qiskit_standard,qiskit_standard,0.126907,101,56,56,129,52,11
17,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_standard,tket,qft_8__qiskit_ai__qiskit_standard__tket,1.256950,89,...,qiskit_ai,qiskit_standard,tket,1.093350,108,56,56,129,0,-19
18,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,tket,qiskit_ai,qft_8__qiskit_ai__tket__qiskit_ai,1.431439,103,...,qiskit_ai,tket,qiskit_ai,1.255780,101,56,56,129,23,2
19,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,tket,qiskit_standard,qft_8__qiskit_ai__tket__qiskit_standard,1.285987,142,...,qiskit_ai,tket,qiskit_standard,1.066856,108,56,56,129,47,34
20,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,tket,tket,qft_8__qiskit_ai__tket__tket,2.150858,77,...,qiskit_ai,tket,tket,2.088341,108,56,56,129,0,-31
21,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_ai,qiskit_ai,qft_8__qiskit_standard__qiskit_ai__qiskit_ai,0.496869,114,...,qiskit_standard,qiskit_ai,qiskit_ai,0.231230,101,56,56,129,51,13
22,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_ai,qiskit_standard,qft_8__qiskit_standard__qiskit_ai__qiskit_stan...,0.329206,114,...,qiskit_standard,qiskit_ai,qiskit_standard,0.118306,101,56,56,129,51,13
23,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_ai,tket,qft_8__qiskit_standard__qiskit_ai__tket,1.385695,78,...,qiskit_standard,qiskit_ai,tket,1.186686,108,56,56,129,0,-30
24,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_standard,qiskit_ai,qft_8__qiskit_standard__qiskit_standard__qiski...,0.260492,114,...,qiskit_standard,qiskit_standard,qiskit_ai,0.140547,101,56,56,129,51,13
25,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_standard,qiskit_standard,qft_8__qiskit_standard__qiskit_standard__qiski...,0.025780,114,...,qiskit_standard,qiskit_standard,qiskit_standard,0.021135,51,56,26,129,51,63
26,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_standard,tket,qft_8__qiskit_standard__qiskit_standard__tket,1.136532,80,...,qiskit_standard,qiskit_standard,tket,0.983606,51,56,26,129,0,29
27,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,tket,qiskit_ai,qft_8__qiskit_standard__tket__qiskit_ai,1.516074,105,...,qiskit_standard,tket,qiskit_ai,1.189470,101,56,56,129,25,4
28,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,tket,qiskit_standard,qft_8__qiskit_standard__tket__qiskit_standard,1.194142,117,...,qiskit_standard,tket,qiskit_standard,0.952818,51,56,26,129,55,66
29,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,tket,tket,qft_8__qiskit_standard__tket__tket,2.070168,74,...,qiskit_standard,tket,tket,1.921506,51,56,26,129,0,23
30,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_ai,qiskit_ai,qft_8__tket__qiskit_ai__qiskit_ai,1.333139,83,...,tket,qiskit_ai,qiskit_ai,1.344650,101,56,56,129,23,-18
31,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_ai,qiskit_standard,qft_8__tket__qiskit_ai__qiskit_standard,1.208829,112,...,tket,qiskit_ai,qiskit_standard,1.188238,101,56,56,129,49,11
32,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_ai,tket,qft_8__tket__qiskit_ai__tket,2.153197,77,...,tket,qiskit_ai,tket,2.066658,108,56,56,129,0,-31
33,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_standard,qiskit_ai,qft_8__tket__qiskit_standard__qiskit_ai,1.113815,99,...,tket,qiskit_standard,qiskit_ai,1.043704,101,56,56,129,45,-2
34,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_standard,qiskit_standard,qft_8__tket__qiskit_standard__qiskit_standard,0.928853,110,...,tket,qiskit_standard,qiskit_standard,0.952112,51,56,26,129,52,59
35,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_standard,tket,qft_8__tket__qiskit_standard__tket,1.983456,82,...,tket,qiskit_standard,tket,1.908197,51,56,26,129,0,31
36,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,tket,qiskit_ai,qft_8__tket__tket__qiskit_ai,2.042704,80,...,tket,tket,qiskit_ai,1.970820,101,56,56,129,23,-21
37,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,tket,qiskit_standard,qft_8__tket__tket__qiskit_standard,1.844736,111,...,tket,tket,qiskit_standard,1.900990,51,56,26,129,51,60
38,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,tket,tket,qft_8__tket__tket__tket,2.732051,51,...,tket,tket,tket,2.790288,51,56,26,129,0,0

In [8]:
#Optimize only is on average 26 fewer two qubit gates than hardware aware.
merged["two_qubit_gate_difference"].describe()

count    39.000000
mean     25.948718
std      24.335321
min      -5.000000
25%       0.000000
50%      24.000000
75%      51.000000
max      55.000000
Name: two_qubit_gate_difference, dtype: float64

In [9]:
# Depth is less drastic difference, but still noticable
merged["depth_difference"].describe()

count    39.000000
mean      5.820513
std      37.588402
min     -77.000000
25%     -18.500000
50%      11.000000
75%      28.000000
max      66.000000
Name: depth_difference, dtype: float64

In [14]:
qiskit_ai = merged[merged["opt_chain"].str.contains("qiskit_ai")]
qiskit_ai

,circuit_hardware,optimizer_hardware,artifact_path_hardware,opt_level_hardware,opt_1_hardware,opt_2_hardware,opt_3_hardware,opt_chain,runtime_hardware,final_depth_hardware,...,opt_1_optimize,opt_2_optimize,opt_3_optimize,runtime_optimize,final_depth_optimize,final_two_qubit_gate_count_optimize,final_two_qubit_depth_optimize,final_total_gates_optimize,two_qubit_gate_difference,depth_difference
0,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,1,qiskit_ai,NaN,NaN,qft_8__qiskit_ai,1.002103,31,...,qiskit_ai,NaN,NaN,0.843884,108,56,56,164,-4,-77
3,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_ai,qiskit_ai,NaN,qft_8__qiskit_ai__qiskit_ai,0.418219,31,...,qiskit_ai,qiskit_ai,NaN,0.471388,108,56,56,164,-5,-77
4,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_ai,qiskit_standard,NaN,qft_8__qiskit_ai__qiskit_standard,0.178461,100,...,qiskit_ai,qiskit_standard,NaN,0.170455,101,56,56,129,45,-1
5,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_ai,tket,NaN,qft_8__qiskit_ai__tket,1.393332,79,...,qiskit_ai,tket,NaN,1.345175,108,56,56,129,0,-29
6,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_standard,qiskit_ai,NaN,qft_8__qiskit_standard__qiskit_ai,0.269955,114,...,qiskit_standard,qiskit_ai,NaN,0.124261,101,56,56,129,51,13
9,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,tket,qiskit_ai,NaN,qft_8__tket__qiskit_ai,1.136095,80,...,tket,qiskit_ai,NaN,1.221084,101,56,56,129,24,-21
12,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_ai,qiskit_ai,qft_8__qiskit_ai__qiskit_ai__qiskit_ai,0.433238,31,...,qiskit_ai,qiskit_ai,qiskit_ai,0.386378,108,56,56,164,-5,-77
13,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_ai,qiskit_standard,qft_8__qiskit_ai__qiskit_ai__qiskit_standard,0.258436,114,...,qiskit_ai,qiskit_ai,qiskit_standard,0.238175,101,56,56,129,51,13
14,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_ai,tket,qft_8__qiskit_ai__qiskit_ai__tket,1.313719,91,...,qiskit_ai,qiskit_ai,tket,1.198725,108,56,56,129,0,-17
15,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_standard,qiskit_ai,qft_8__qiskit_ai__qiskit_standard__qiskit_ai,0.392284,114,...,qiskit_ai,qiskit_standard,qiskit_ai,0.247000,101,56,56,129,51,13
16,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_standard,qiskit_standard,qft_8__qiskit_ai__qiskit_standard__qiskit_stan...,0.144979,112,...,qiskit_ai,qiskit_standard,qiskit_standard,0.126907,101,56,56,129,52,11
17,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,qiskit_standard,tket,qft_8__qiskit_ai__qiskit_standard__tket,1.256950,89,...,qiskit_ai,qiskit_standard,tket,1.093350,108,56,56,129,0,-19
18,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,tket,qiskit_ai,qft_8__qiskit_ai__tket__qiskit_ai,1.431439,103,...,qiskit_ai,tket,qiskit_ai,1.255780,101,56,56,129,23,2
19,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,tket,qiskit_standard,qft_8__qiskit_ai__tket__qiskit_standard,1.285987,142,...,qiskit_ai,tket,qiskit_standard,1.066856,108,56,56,129,47,34
20,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_ai,tket,tket,qft_8__qiskit_ai__tket__tket,2.150858,77,...,qiskit_ai,tket,tket,2.088341,108,56,56,129,0,-31
21,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_ai,qiskit_ai,qft_8__qiskit_standard__qiskit_ai__qiskit_ai,0.496869,114,...,qiskit_standard,qiskit_ai,qiskit_ai,0.231230,101,56,56,129,51,13
22,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_ai,qiskit_standard,qft_8__qiskit_standard__qiskit_ai__qiskit_stan...,0.329206,114,...,qiskit_standard,qiskit_ai,qiskit_standard,0.118306,101,56,56,129,51,13
23,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_ai,tket,qft_8__qiskit_standard__qiskit_ai__tket,1.385695,78,...,qiskit_standard,qiskit_ai,tket,1.186686,108,56,56,129,0,-30
24,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_standard,qiskit_ai,qft_8__qiskit_standard__qiskit_standard__qiski...,0.260492,114,...,qiskit_standard,qiskit_standard,qiskit_ai,0.140547,101,56,56,129,51,13
27,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,tket,qiskit_ai,qft_8__qiskit_standard__tket__qiskit_ai,1.516074,105,...,qiskit_standard,tket,qiskit_ai,1.189470,101,56,56,129,25,4
30,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_ai,qiskit_ai,qft_8__tket__qiskit_ai__qiskit_ai,1.333139,83,...,tket,qiskit_ai,qiskit_ai,1.344650,101,56,56,129,23,-18
31,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_ai,qiskit_standard,qft_8__tket__qiskit_ai__qiskit_standard,1.208829,112,...,tket,qiskit_ai,qiskit_standard,1.188238,101,56,56,129,49,11
32,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_ai,tket,qft_8__tket__qiskit_ai__tket,2.153197,77,...,tket,qiskit_ai,tket,2.066658,108,56,56,129,0,-31
33,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_standard,qiskit_ai,qft_8__tket__qiskit_standard__qiskit_ai,1.113815,99,...,tket,qiskit_standard,qiskit_ai,1.043704,101,56,56,129,45,-2
36,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,tket,qiskit_ai,qft_8__tket__tket__qiskit_ai,2.042704,80,...,tket,tket,qiskit_ai,1.970820,101,56,56,129,23,-21

In [15]:
qiskit_ai["two_qubit_gate_difference"].describe()

count    25.000000
mean     25.920000
std      23.298641
min      -5.000000
25%       0.000000
50%      24.000000
75%      51.000000
max      52.000000
Name: two_qubit_gate_difference, dtype: float64

In [16]:
qiskit_standard_only = merged[~merged["opt_chain"].str.contains("qiskit_ai")]
qiskit_standard_only

,circuit_hardware,optimizer_hardware,artifact_path_hardware,opt_level_hardware,opt_1_hardware,opt_2_hardware,opt_3_hardware,opt_chain,runtime_hardware,final_depth_hardware,...,opt_1_optimize,opt_2_optimize,opt_3_optimize,runtime_optimize,final_depth_optimize,final_two_qubit_gate_count_optimize,final_two_qubit_depth_optimize,final_total_gates_optimize,two_qubit_gate_difference,depth_difference
1,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,1,qiskit_standard,NaN,NaN,qft_8__qiskit_standard,0.020029,112,...,qiskit_standard,NaN,NaN,0.012383,51,56,26,129,52,61
2,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,1,tket,NaN,NaN,qft_8__tket,1.145792,51,...,tket,NaN,NaN,1.059701,51,56,26,129,0,0
7,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_standard,qiskit_standard,NaN,qft_8__qiskit_standard__qiskit_standard,0.023073,111,...,qiskit_standard,qiskit_standard,NaN,0.012297,51,56,26,129,52,60
8,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,qiskit_standard,tket,NaN,qft_8__qiskit_standard__tket,1.203237,78,...,qiskit_standard,tket,NaN,0.968230,51,56,26,129,0,27
10,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,tket,qiskit_standard,NaN,qft_8__tket__qiskit_standard,0.941959,110,...,tket,qiskit_standard,NaN,0.949602,51,56,26,129,51,59
11,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,2,tket,tket,NaN,qft_8__tket__tket,1.846858,51,...,tket,tket,NaN,1.993882,51,56,26,129,0,0
25,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_standard,qiskit_standard,qft_8__qiskit_standard__qiskit_standard__qiski...,0.025780,114,...,qiskit_standard,qiskit_standard,qiskit_standard,0.021135,51,56,26,129,51,63
26,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,qiskit_standard,tket,qft_8__qiskit_standard__qiskit_standard__tket,1.136532,80,...,qiskit_standard,qiskit_standard,tket,0.983606,51,56,26,129,0,29
28,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,tket,qiskit_standard,qft_8__qiskit_standard__tket__qiskit_standard,1.194142,117,...,qiskit_standard,tket,qiskit_standard,0.952818,51,56,26,129,55,66
29,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,qiskit_standard,tket,tket,qft_8__qiskit_standard__tket__tket,2.070168,74,...,qiskit_standard,tket,tket,1.921506,51,56,26,129,0,23
34,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_standard,qiskit_standard,qft_8__tket__qiskit_standard__qiskit_standard,0.928853,110,...,tket,qiskit_standard,qiskit_standard,0.952112,51,56,26,129,52,59
35,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,qiskit_standard,tket,qft_8__tket__qiskit_standard__tket,1.983456,82,...,tket,qiskit_standard,tket,1.908197,51,56,26,129,0,31
37,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,tket,qiskit_standard,qft_8__tket__tket__qiskit_standard,1.844736,111,...,tket,tket,qiskit_standard,1.900990,51,56,26,129,51,60
38,qft_8,chain,brute_force_chains/cheap_optimizers/initial_te...,3,tket,tket,tket,qft_8__tket__tket__tket,2.732051,51,...,tket,tket,tket,2.790288,51,56,26,129,0,0

In [17]:
qiskit_standard_only["two_qubit_gate_difference"].describe()

count    14.000000
mean     26.000000
std      26.998575
min       0.000000
25%       0.000000
50%      25.500000
75%      51.750000
max      55.000000
Name: two_qubit_gate_difference, dtype: float64