In [12]:
path = "../Quantum_Circuit_Optimization_Data/trajectories_combined.db"

In [13]:
import sqlite3

In [14]:
conn = sqlite3.connect(path)

In [15]:
import pandas as pd

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table';
    """,
    conn
)

print("Table Names:")
print(tables)

Table Names:
                name
0           circuits
1    sqlite_sequence
2         optimizers
3  optimization_runs
4       trajectories
5   trajectory_steps

In [16]:
## All 5 Optimizers used during testing
opt_df = pd.read_sql_query(
    "SELECT * FROM optimizers;",
    conn
)
opt_df

,id,name,runner_type,options_json,description
0,1,wisq_rules,wisq,"{""approx_epsilon"": 0}",WISQ with rules-only optimization (no resynthe...
1,2,wisq_bqskit,wisq,"{""approx_epsilon"": 1e-10, ""opt_timeout"": 300}",WISQ with BQSKit resynthesis
2,3,tket,tket,"{""gate_set"": ""IBMN""}",TKET FullPeepholeOptimise with IBMN gate set
3,4,qiskit_ai,qiskit_ai,"{""optimization_levels"": [3], ""iterations_per_l...",Qiskit AI transpiler at optimization level 3
4,5,qiskit_standard,qiskit_standard,"{""optimization_levels"": [3]}",Standard Qiskit transpiler at optimization lev...

In [17]:
traj_df = pd.read_sql_query(
    "SELECT * FROM trajectories;",
    conn
)
print(traj_df[traj_df["circuit_id"] == 1].iloc[6]["metadata_json"])
traj_df[traj_df["circuit_id"] == 1]

{"source": "synthesized_from_optimization_runs", "run_id": 336}

,id,circuit_id,chain_name,num_steps,initial_depth,initial_two_qubit_gates,initial_two_qubit_depth,initial_total_gates,final_depth,final_two_qubit_gates,final_two_qubit_depth,final_total_gates,total_duration_seconds,total_reward,improvement_percentage,metadata_json,created_at
0,1,1,single_1,1,17,18,11,78,23,18,11,138,600.292814,-60.039281,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
1,2,1,single_1,1,17,18,11,78,23,18,11,138,600.192577,-60.029258,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
2,3,1,single_2,1,17,18,11,78,45,13,9,73,402.726940,-40.004916,27.777778,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
3,4,1,single_2,1,17,18,11,78,34,12,9,59,422.451553,-41.921822,33.333333,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
4,5,1,single_2,1,17,18,11,78,27,12,9,45,540.983333,-53.775000,33.333333,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
5,6,1,single_3,1,17,18,11,78,11,18,11,18,1.457696,-0.155770,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
6,7,1,single_3,1,17,18,11,78,11,18,11,18,1.391856,-0.149186,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
7,8,1,single_3,1,17,18,11,78,11,18,11,18,1.641361,-0.174136,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
8,9,1,single_3,1,17,18,11,78,11,18,11,18,1.337283,-0.143728,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
9,10,1,single_3,1,17,18,11,78,11,18,11,18,1.611156,-0.171116,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
10,11,1,single_3,1,17,18,11,78,11,18,11,18,1.464161,-0.156416,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
11,12,1,single_3,1,17,18,11,78,11,18,11,18,1.326651,-0.142665,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
12,13,1,single_3,1,17,18,11,78,11,18,11,18,1.641461,-0.174146,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
13,14,1,single_4,1,17,18,11,78,17,18,11,78,0.329484,-0.042948,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
14,15,1,single_4,1,17,18,11,78,17,18,11,78,0.414190,-0.051419,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
15,16,1,single_4,1,17,18,11,78,17,18,11,78,0.402045,-0.050204,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
16,17,1,single_4,1,17,18,11,78,17,18,11,78,0.385018,-0.048502,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
17,18,1,single_4,1,17,18,11,78,17,18,11,78,0.366843,-0.046684,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
18,19,1,single_4,1,17,18,11,78,17,18,11,78,0.350958,-0.045096,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
19,20,1,single_4,1,17,18,11,78,17,18,11,78,0.425965,-0.052596,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
20,21,1,single_4,1,17,18,11,78,17,18,11,78,0.390253,-0.049025,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
21,22,1,single_4,1,17,18,11,78,17,18,11,78,0.457423,-0.055742,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
22,23,1,single_5,1,17,18,11,78,11,18,11,18,0.967805,-0.106780,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
23,24,1,single_5,1,17,18,11,78,11,18,11,18,1.302154,-0.140215,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
24,25,1,single_5,1,17,18,11,78,11,18,11,18,0.175187,-0.027519,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
25,26,1,single_5,1,17,18,11,78,11,18,11,18,0.424177,-0.052418,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
26,27,1,single_5,1,17,18,11,78,11,18,11,18,0.191505,-0.029150,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
27,28,1,single_5,1,17,18,11,78,11,18,11,18,1.368164,-0.146816,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
28,29,1,single_5,1,17,18,11,78,11,18,11,18,0.194897,-0.029490,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
29,30,1,single_5,1,17,18,11,78,11,18,11,18,0.473846,-0.057385,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
30,31,1,single_5,1,17,18,11,78,11,18,11,18,0.214367,-0.031437,0.000000,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34

In [18]:
print(traj_df[traj_df["circuit_id"] == 9].iloc[7]["metadata_json"])
traj_df[traj_df["circuit_id"] == 9]

{"source": "synthesized_from_optimization_runs", "run_id": 495}

,id,circuit_id,chain_name,num_steps,initial_depth,initial_two_qubit_gates,initial_two_qubit_depth,initial_total_gates,final_depth,final_two_qubit_gates,final_two_qubit_depth,final_total_gates,total_duration_seconds,total_reward,improvement_percentage,metadata_json,created_at
209,210,9,single_1,1,14,4,4,20,54,23,23,74,600.056248,-64.765625,-475.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
210,211,9,single_1,1,14,4,4,20,55,22,20,73,600.242328,-64.534233,-450.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
211,212,9,single_2,1,14,4,4,20,49,20,18,71,301.476235,-34.157623,-400.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
212,213,9,single_2,1,14,4,4,20,79,18,18,108,301.523428,-33.662343,-350.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
213,214,9,single_3,1,14,4,4,20,49,24,22,64,1.055774,-5.115577,-500.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
214,215,9,single_3,1,14,4,4,20,49,24,22,64,0.893341,-5.099334,-500.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
215,216,9,single_3,1,14,4,4,20,49,24,22,64,0.877677,-5.097768,-500.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
216,217,9,single_3,1,14,4,4,20,49,24,22,64,1.011537,-5.111154,-500.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
217,218,9,single_3,1,14,4,4,20,49,24,22,64,0.905144,-5.100514,-500.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
218,219,9,single_3,1,14,4,4,20,49,24,22,64,1.180121,-5.128012,-500.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
219,220,9,single_3,1,14,4,4,20,49,24,22,64,0.894838,-5.099484,-500.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
220,221,9,single_3,1,14,4,4,20,49,24,22,64,0.941339,-5.104134,-500.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
221,222,9,single_4,1,14,4,4,20,8,0,0,16,0.137871,0.976213,100.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
222,223,9,single_5,1,14,4,4,20,82,32,30,120,0.033399,-7.013340,-700.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
223,224,9,single_5,1,14,4,4,20,84,32,30,121,0.027492,-7.012749,-700.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
224,225,9,single_5,1,14,4,4,20,81,32,30,118,0.047932,-7.014793,-700.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
225,226,9,single_5,1,14,4,4,20,85,32,30,122,0.033011,-7.013301,-700.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
226,227,9,single_5,1,14,4,4,20,83,34,32,112,0.042170,-7.514217,-750.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
227,228,9,single_5,1,14,4,4,20,86,32,30,121,0.028777,-7.012878,-700.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
228,229,9,single_5,1,14,4,4,20,82,32,30,120,0.044303,-7.014430,-700.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34
229,230,9,single_5,1,14,4,4,20,78,36,34,102,0.022198,-8.012220,-800.0,"{""source"": ""synthesized_from_optimization_runs...",2026-03-05 20:39:34

In [19]:
traj_steps_df = pd.read_sql_query(
    "SELECT * FROM trajectory_steps;",
    conn
)
pd.set_option('display.max_columns', None)
traj_steps_df[traj_steps_df["trajectory_id"] == 7827]

,id,trajectory_id,step_index,optimizer_id,state_depth,state_two_qubit_gates,state_two_qubit_depth,state_total_gates,state_num_qubits,state_gate_density,state_two_qubit_ratio,state_steps_taken,state_time_budget_remaining,state_category_json,next_state_depth,next_state_two_qubit_gates,next_state_two_qubit_depth,next_state_total_gates,next_state_gate_density,next_state_two_qubit_ratio,next_state_steps_taken,next_state_time_budget_remaining,reward_improvement_only,reward_efficiency,reward_multi_objective,reward_sparse_final,reward_category_relative,reward_efficiency_normalized,done,duration_seconds,created_at
14202,14203,7827,0,4,68,39,32,183,6,30.5,0.213115,0,300.000000,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",135,111,86,255,42.500000,0.435294,1,299.208322,-1.846154,-1.935322,-1.677064,0.000000,-0.956201,-1.856418,0,0.791678,2026-03-05 20:40:45
14203,14204,7827,1,5,135,111,86,255,6,42.5,0.435294,1,299.208322,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",132,99,76,239,39.833333,0.414226,2,299.135098,0.108108,0.090786,0.065020,-1.538462,1.350584,0.098084,1,0.073224,2026-03-05 20:40:45

In [20]:
local[local["id"] == 623]

NameError: name 'local' is not defined

In [21]:
print(artifact.loc[artifact["id"] == 650, "name"].iloc[0])

NameError: name 'artifact' is not defined

In [22]:
local[local["name"] == "barenco_tof_3"]

NameError: name 'local' is not defined

In [23]:
artifact[artifact["name"] == "artifact_qaoa_barabasi_albert_N6_3reps__wisq_rules"]

NameError: name 'artifact' is not defined

In [29]:
# Original Circuits
circuit_df = pd.read_sql_query(
    "SELECT * FROM circuits;",
    conn
)
circuit_df["optimizer_chain"] = circuit_df["name"].str.split("__").str[1]
circuit_df["original_circuit"] = circuit_df["name"].str.split("__").str[0].str.replace(r"^(artifact_)+", "", regex=True)

local = circuit_df[circuit_df["source"] == "local"]
local
circuit_df.to_csv("circuits.csv")

In [25]:
# Circuits Created by Optimization of Other Circuits
artifact = circuit_df[circuit_df["source"] == "artifact"]
artifact

,id,name,category,source,qasm_path,num_qubits,initial_depth,initial_two_qubit_gates,initial_two_qubit_depth,initial_total_gates,gate_density,two_qubit_ratio,created_at,optimizer_chain,original_circuit
111,112,artifact_qft_16__tket,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/q...,16,107,240,58,513,32.062500,0.467836,2026-03-05 20:39:34,tket,qft_16
112,113,artifact_qft_16__qiskit_standard,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/q...,16,255,541,160,1138,71.125000,0.475395,2026-03-05 20:39:34,qiskit_standard,qft_16
113,114,artifact_qft_16__wisq_bqskit,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/q...,16,381,259,80,1790,111.875000,0.144693,2026-03-05 20:39:34,wisq_bqskit,qft_16
114,115,artifact_qft_16__wisq_rules,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/q...,16,341,264,69,1964,122.750000,0.134420,2026-03-05 20:39:34,wisq_rules,qft_16
115,116,artifact_qft_12__tket,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/q...,12,79,132,42,289,24.083333,0.456747,2026-03-05 20:39:34,tket,qft_12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2811,2812,artifact_artifact_qft_N006__wisq_rules__tket,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts_s...,6,41,30,24,65,10.833333,0.461538,2026-03-05 20:40:43,wisq_rules,qft_N006
2812,2813,artifact_artifact_qft_N006__wisq_rules__qiskit...,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts_s...,6,102,78,70,133,22.166667,0.586466,2026-03-05 20:40:43,wisq_rules,qft_N006
2813,2814,artifact_artifact_qft_N006__wisq_rules__qiskit_ai,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts_s...,6,117,86,77,152,25.333333,0.565789,2026-03-05 20:40:43,wisq_rules,qft_N006
2814,2815,artifact_artifact_qft_N006__wisq_rules__wisq_b...,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts_s...,6,109,33,28,230,38.333333,0.143478,2026-03-05 20:40:43,wisq_rules,qft_N006
2815,2816,artifact_artifact_qft_N006__wisq_rules__wisq_r...,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts_s...,6,75,34,29,100,16.666667,0.340000,2026-03-05 20:40:43,wisq_rules,qft_N006

In [26]:
sample = artifact.iloc[:100]
sample["optimizer_chain"] = sample["name"].str.split("__").str[1]
sample["original_circuit"] = sample["name"].str.split("__").str[0].str.strip("artifact_")
sample

,id,name,category,source,qasm_path,num_qubits,initial_depth,initial_two_qubit_gates,initial_two_qubit_depth,initial_total_gates,gate_density,two_qubit_ratio,created_at,optimizer_chain,original_circuit
111,112,artifact_qft_16__tket,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/q...,16,107,240,58,513,32.062500,0.467836,2026-03-05 20:39:34,tket,qft_16
112,113,artifact_qft_16__qiskit_standard,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/q...,16,255,541,160,1138,71.125000,0.475395,2026-03-05 20:39:34,qiskit_standard,qft_16
113,114,artifact_qft_16__wisq_bqskit,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/q...,16,381,259,80,1790,111.875000,0.144693,2026-03-05 20:39:34,wisq_bqskit,qft_16
114,115,artifact_qft_16__wisq_rules,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/q...,16,341,264,69,1964,122.750000,0.134420,2026-03-05 20:39:34,wisq_rules,qft_16
115,116,artifact_qft_12__tket,qft,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/q...,12,79,132,42,289,24.083333,0.456747,2026-03-05 20:39:34,tket,qft_12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,207,artifact_barenco_tof_10__tket,feynman,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/b...,19,428,178,162,588,30.947368,0.302721,2026-03-05 20:39:36,tket,barenco_tof_10
207,208,artifact_barenco_tof_10__qiskit_standard,feynman,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/b...,19,635,325,298,879,46.263158,0.369738,2026-03-05 20:39:36,qiskit_standard,barenco_tof_10
208,209,artifact_barenco_tof_10__qiskit_ai,feynman,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/b...,19,12,0,0,98,5.157895,0.000000,2026-03-05 20:39:36,qiskit_ai,barenco_tof_10
209,210,artifact_barenco_tof_10__wisq_bqskit,feynman,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/b...,19,458,156,143,637,33.526316,0.244898,2026-03-05 20:39:36,wisq_bqskit,barenco_tof_10
210,211,artifact_barenco_tof_10__wisq_rules,feynman,artifact,/home/lbaird/repos/qdev-laura/data/artifacts/b...,19,375,161,154,465,24.473684,0.346237,2026-03-05 20:39:36,wisq_rules,barenco_tof_10

In [27]:
import pandas as pd

master_df = pd.DataFrame(columns=[
    "id",
    "parent_id",
    "chain_name",
    "original_circuit",
    "opt_1",
    "opt_2",
    "opt_3",
    "qasm_path",
    "initial_num_qubits",
    "initial_depth",
    "initial_two_qubit_gates",
    "initial_total_gates",
    "final_num_qubits",
    "final_depth",
    "final_two_qubit_gates",
    "final_total_gates"
])

print(master_df.head())

Empty DataFrame
Columns: [id, parent_id, chain_name, original_circuit, opt_1, opt_2, opt_3, qasm_path, initial_num_qubits, initial_depth, initial_two_qubit_gates, initial_total_gates, final_num_qubits, final_depth, final_two_qubit_gates, final_total_gates]
Index: []

In [125]:
## Creates df with all calculated chains
## Do not trust data for initial. 
## It likely is using info from intermediate step, not initial circuit.

import numpy as np
import json
master_df = pd.DataFrame(columns=[
    "id",
    "parent_circuit_id",
    "chain_name",
    "original_circuit",
    "original_category",
    "original_circuit_path",
    "opt_1",
    "opt_2",
    "opt_3",
    "qasm_path",
    "initial_num_qubits",
    "initial_depth",
    "initial_two_qubit_gates",
    "initial_total_gates",
    "final_num_qubits",
    "final_depth",
    "final_two_qubit_gates",
    "final_total_gates"
])

for index, row in traj_df.iterrows():
    parent_name = ""
    chain_name = ""
    original_circuit = ""
    opt_1 = "N/A"
    opt_2 = "N/A"
    opt_3 = "N/A"
    qasm_path = "N/A"
    initial_num_qubits = -1
    initial_depth = -1
    initial_two_qubit_gates = 0
    initial_total_gates = 0
    final_num_qubits = 0
    final_depth = 0
    final_two_qubit_gates = 0
    final_total_gates = 0

    
    metadata = json.loads(row["metadata_json"])

    parent_circuit_id = row["circuit_id"]
    chain_name = row["chain_name"]
    
    #final_num_qubits       = row["final_num_qubits"]
    final_depth             = row["final_depth"]
    final_two_qubit_gates   = row["final_two_qubit_gates"]
    final_total_gates       = row["final_total_gates"]
    original_circuit        = circuit_df.loc[circuit_df["id"] == row["circuit_id"]]["original_circuit"].values[0]
    original_category       = local.loc[local["name"] == original_circuit]["category"].values[0]
    original_circuit_path   = local.loc[local["name"] == original_circuit]["qasm_path"].values[0]


    initial_num_qubits      = local.loc[local["name"] == original_circuit]["num_qubits"].values[0]
    initial_depth           = local.loc[local["name"] == original_circuit]["initial_depth"].values[0]
    initial_two_qubit_gates = local.loc[local["name"] == original_circuit]["initial_two_qubit_gates"].values[0]
    initial_total_gates     = local.loc[local["name"] == original_circuit]["initial_total_gates"].values[0]
    
    if "single" in chain_name:
        opt_id = int(chain_name.split("_")[-1])
        opt_1 = opt_df.loc[opt_df["id"] == opt_id]["name"].values[0] 
    else:        
        opt_1 = metadata.get("step1_optimizer", "N/A")
        opt_2 = metadata.get("step2_optimizer", "N/A")
        opt_3 = metadata.get("step3_optimizer", "N/A")
        parent_circuit = metadata.get("original_circuit")
        split = parent_circuit.split("__")
        if len(split) == 2:
            temp_1 = opt_1
            temp_2 = opt_2
            opt_1 = split[1]
            tpt_2 = temp_1
            opt_3 = temp_2
        elif len(split) == 3:
            temp_1 = opt_1
            opt_1 = split[1]
            tpt_2 = split[2]
            opt_3 = temp_1
            

    

    master_df.loc[len(master_df)] = [
        index + 1,
        parent_circuit_id,
        chain_name,
        original_circuit,
        original_category,
        original_circuit_path,
        opt_1,
        opt_2,
        opt_3,
        qasm_path,
        initial_num_qubits,
        initial_depth,
        initial_two_qubit_gates,
        initial_total_gates,
        final_num_qubits,
        final_depth,
        final_two_qubit_gates,
        final_total_gates,
    ]


master_df = master_df.replace("N/A", np.nan)
## Adds entire circuit path in format original_circuit__opt1__opt2__opt3
master_df["opt_chain"] = master_df.apply(
    lambda row: "__".join(
        [str(x) for x in [
            row["original_circuit"],
            row["opt_1"],
            row["opt_2"],
            row["opt_3"]
        ] if pd.notna(x)]
    ),
    axis=1
)

In [126]:
master_df[5000:]

,id,parent_circuit_id,chain_name,original_circuit,original_category,original_circuit_path,opt_1,opt_2,opt_3,qasm_path,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,opt_chain
5000,5001,1818,chain_tket__qiskit_standard,efficient_su2_12_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12_...,wisq_rules,qiskit_standard,qiskit_standard,NaN,12,19,22,94,0,13,22,22,efficient_su2_12_r2__wisq_rules__qiskit_standa...
5001,5002,1818,chain_tket__tket,efficient_su2_12_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12_...,wisq_rules,tket,tket,NaN,12,19,22,94,0,13,22,22,efficient_su2_12_r2__wisq_rules__tket__tket
5002,5003,1818,chain_tket__wisq_bqskit,efficient_su2_12_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12_...,wisq_rules,wisq_bqskit,wisq_bqskit,NaN,12,19,22,94,0,5,10,10,efficient_su2_12_r2__wisq_rules__wisq_bqskit__...
5003,5004,1818,chain_tket__wisq_rules,efficient_su2_12_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12_...,wisq_rules,wisq_rules,wisq_rules,NaN,12,19,22,94,0,5,10,10,efficient_su2_12_r2__wisq_rules__wisq_rules__w...
5004,5005,1821,chain_wisq_bqskit__qiskit_ai,efficient_su2_12_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12_...,wisq_rules,qiskit_ai,qiskit_ai,NaN,12,19,22,94,0,26,10,89,efficient_su2_12_r2__wisq_rules__qiskit_ai__qi...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16554,16555,1266,chain3_wisq_rules__wisq_bqskit__wisq_bqskit,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,wisq_rules,wisq_bqskit,wisq_bqskit,NaN,5,23,4,23,0,71,18,127,mod5_4__wisq_rules__wisq_bqskit__wisq_bqskit
16555,16556,1266,chain3_wisq_rules__wisq_bqskit__wisq_rules,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,wisq_rules,wisq_bqskit,wisq_rules,NaN,5,23,4,23,0,83,18,133,mod5_4__wisq_rules__wisq_bqskit__wisq_rules
16556,16557,1267,chain3_wisq_rules__wisq_rules__qiskit_ai,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,wisq_rules,wisq_rules,qiskit_ai,NaN,5,23,4,23,0,77,37,94,mod5_4__wisq_rules__wisq_rules__qiskit_ai
16557,16558,1267,chain3_wisq_rules__wisq_rules__qiskit_standard,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,wisq_rules,wisq_rules,qiskit_standard,NaN,5,23,4,23,0,90,51,128,mod5_4__wisq_rules__wisq_rules__qiskit_standard
16558,16559,1267,chain3_wisq_rules__wisq_rules__tket,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,wisq_rules,wisq_rules,tket,NaN,5,23,4,23,0,38,21,49,mod5_4__wisq_rules__wisq_rules__tket

In [109]:
## Number of chains starting with each original circuit
counts = master_df["original_circuit"].value_counts()

print(counts)

original_circuit
efficient_su2_10_r2    306
efficient_su2_12_r2    305
efficient_su2_8        301
efficient_su2_12       298
barenco_tof_3          296
                      ...
hwb8                    26
hwb10                   24
hwb11                   24
qv_N019_12345           24
hwb12                   23
Name: count, Length: 106, dtype: int64

In [110]:
## All unique starting circuits
unique_values = local["name"].tolist()
print(sorted(unique_values))

['W-state', 'adder', 'barenco_tof_10', 'barenco_tof_3', 'barenco_tof_4', 'barenco_tof_5', 'bigadder', 'csla_mux_3', 'efficient_su2_10_r2', 'efficient_su2_12', 'efficient_su2_12_r2', 'efficient_su2_16', 'efficient_su2_8', 'gf2^4_mult', 'gf2^5_mult', 'gf2^6_mult', 'grover_5', 'ham15-high', 'ham15-low', 'ham15-med', 'hwb10', 'hwb11', 'hwb12', 'hwb6', 'hwb8', 'inverseqft1', 'inverseqft2', 'mod5_4', 'mod_mult_55', 'mod_red_21', 'qaoa_barabasi_albert_N10_3reps', 'qaoa_barabasi_albert_N11_3reps', 'qaoa_barabasi_albert_N12_3reps', 'qaoa_barabasi_albert_N13_3reps', 'qaoa_barabasi_albert_N14_3reps', 'qaoa_barabasi_albert_N15_3reps', 'qaoa_barabasi_albert_N16_3reps', 'qaoa_barabasi_albert_N17_3reps', 'qaoa_barabasi_albert_N18_3reps', 'qaoa_barabasi_albert_N19_3reps', 'qaoa_barabasi_albert_N20_3reps', 'qaoa_barabasi_albert_N3_3reps', 'qaoa_barabasi_albert_N4_3reps', 'qaoa_barabasi_albert_N5_3reps', 'qaoa_barabasi_albert_N6_3reps', 'qaoa_barabasi_albert_N7_3reps', 'qaoa_barabasi_albert_N8_3reps', 'qaoa_barabasi_albert_N9_3reps', 'qec', 'qft', 'qft_10', 'qft_12', 'qft_16', 'qft_4', 'qft_8', 'qft_N002', 'qft_N003', 'qft_N004', 'qft_N005', 'qft_N006', 'qft_N007', 'qft_N008', 'qft_N009', 'qft_N010', 'qft_N011', 'qft_N012', 'qft_N013', 'qft_N014', 'qft_N015', 'qft_N016', 'qft_N017', 'qft_N018', 'qft_N019', 'qft_N020', 'qpt', 'qv_N002_12345', 'qv_N003_12345', 'qv_N004_12345', 'qv_N005_12345', 'qv_N006_12345', 'qv_N007_12345', 'qv_N008_12345', 'qv_N009_12345', 'qv_N010_12345', 'qv_N011_12345', 'qv_N012_12345', 'qv_N013_12345', 'qv_N014_12345', 'qv_N015_12345', 'qv_N016_12345', 'qv_N017_12345', 'qv_N018_12345', 'qv_N019_12345', 'qv_N020_12345', 'rb', 'rc_adder_6', 'real_amplitudes_12', 'real_amplitudes_12_r3', 'real_amplitudes_16_r2', 'real_amplitudes_8', 'real_amplitudes_8_r2', 'square_heisenberg_N16', 'square_heisenberg_N4', 'square_heisenberg_N9', 'teleport', 'teleportv2', 'tof_10', 'tof_3', 'tof_4', 'tof_5', 'vbe_adder_3']

In [111]:
counts = circuit_df["original_circuit"].value_counts()

print(counts)

original_circuit
efficient_su2_10_r2    31
efficient_su2_12       31
efficient_su2_12_r2    31
efficient_su2_8        31
barenco_tof_3          31
                       ..
inverseqft1             1
inverseqft2             1
qec                     1
teleport                1
teleportv2              1
Name: count, Length: 111, dtype: int64

In [112]:
# Shows how many unique chains from each starting circuit
# Should have 155 if all have been completed

unique_counts = (
    master_df
    .drop_duplicates(subset=["original_circuit", "opt_1", "opt_2", "opt_3"])
    .groupby("original_circuit")
    .size()
    .sort_index()
)

print(unique_counts)

original_circuit
W-state            81
adder              93
barenco_tof_10     30
barenco_tof_3     155
barenco_tof_4     154
                 ...
tof_10             30
tof_3              55
tof_4              55
tof_5              55
vbe_adder_3        55
Length: 106, dtype: int64

In [113]:
for circuit, count in unique_counts.items():
    print(f"{circuit}: {count}")

W-state: 81
adder: 93
barenco_tof_10: 30
barenco_tof_3: 155
barenco_tof_4: 154
barenco_tof_5: 155
bigadder: 93
csla_mux_3: 152
efficient_su2_10_r2: 155
efficient_su2_12: 152
efficient_su2_12_r2: 155
efficient_su2_16: 147
efficient_su2_8: 154
gf2^4_mult: 154
gf2^5_mult: 153
gf2^6_mult: 153
grover_5: 155
ham15-high: 26
ham15-low: 150
ham15-med: 104
hwb10: 20
hwb11: 20
hwb12: 19
hwb6: 30
hwb8: 20
mod5_4: 154
mod_mult_55: 55
mod_red_21: 55
qaoa_barabasi_albert_N10_3reps: 55
qaoa_barabasi_albert_N11_3reps: 55
qaoa_barabasi_albert_N12_3reps: 55
qaoa_barabasi_albert_N13_3reps: 54
qaoa_barabasi_albert_N14_3reps: 55
qaoa_barabasi_albert_N15_3reps: 55
qaoa_barabasi_albert_N16_3reps: 54
qaoa_barabasi_albert_N17_3reps: 54
qaoa_barabasi_albert_N18_3reps: 55
qaoa_barabasi_albert_N19_3reps: 30
qaoa_barabasi_albert_N20_3reps: 30
qaoa_barabasi_albert_N3_3reps: 55
qaoa_barabasi_albert_N4_3reps: 55
qaoa_barabasi_albert_N5_3reps: 55
qaoa_barabasi_albert_N6_3reps: 55
qaoa_barabasi_albert_N7_3reps: 55
qaoa_barabasi_albert_N8_3reps: 55
qaoa_barabasi_albert_N9_3reps: 55
qft: 54
qft_10: 55
qft_12: 55
qft_16: 43
qft_4: 55
qft_8: 55
qft_N002: 55
qft_N003: 55
qft_N004: 55
qft_N005: 55
qft_N006: 55
qft_N007: 55
qft_N008: 55
qft_N009: 54
qft_N010: 54
qft_N011: 55
qft_N012: 55
qft_N013: 55
qft_N014: 54
qft_N015: 55
qft_N016: 55
qft_N017: 54
qft_N018: 53
qft_N019: 30
qft_N020: 28
qpt: 31
qv_N002_12345: 55
qv_N003_12345: 55
qv_N004_12345: 55
qv_N005_12345: 55
qv_N006_12345: 55
qv_N007_12345: 55
qv_N008_12345: 54
qv_N009_12345: 54
qv_N010_12345: 52
qv_N011_12345: 52
qv_N012_12345: 49
qv_N013_12345: 48
qv_N014_12345: 48
qv_N015_12345: 37
qv_N016_12345: 45
qv_N017_12345: 37
qv_N018_12345: 38
qv_N019_12345: 20
qv_N020_12345: 27
rb: 55
rc_adder_6: 54
real_amplitudes_12: 55
real_amplitudes_12_r3: 55
real_amplitudes_16_r2: 55
real_amplitudes_8: 55
real_amplitudes_8_r2: 55
square_heisenberg_N16: 54
square_heisenberg_N4: 55
square_heisenberg_N9: 55
tof_10: 30
tof_3: 55
tof_4: 55
tof_5: 55
vbe_adder_3: 55

In [115]:
#All original circuits
og_circuits = local["name"].dropna().unique().tolist()
#All optimizers used
optimizers = ["wisq_rules", "wisq_bqskit", "tket", "qiskit_ai", "qiskit_standard"]

##All computed chains
unique_opt_chains = master_df["opt_chain"].dropna().unique().tolist()

In [116]:
og_circuits_master = master_df["original_circuit"].dropna().unique().tolist()
len(og_circuits_master)

106

In [117]:
#Finds all possible chains for each circuit

from itertools import product
all_possible_chains = []

for circuit in og_circuits:
    for chain_length in range(1, 4):
        for chain in product(optimizers, repeat=chain_length):
            opt_chain = "__".join([circuit] + list(chain))
            all_possible_chains.append(opt_chain)

print(len(all_possible_chains))
print(all_possible_chains[-10:])

17205
['square_heisenberg_N9__qiskit_standard__qiskit_ai__wisq_rules', 'square_heisenberg_N9__qiskit_standard__qiskit_ai__wisq_bqskit', 'square_heisenberg_N9__qiskit_standard__qiskit_ai__tket', 'square_heisenberg_N9__qiskit_standard__qiskit_ai__qiskit_ai', 'square_heisenberg_N9__qiskit_standard__qiskit_ai__qiskit_standard', 'square_heisenberg_N9__qiskit_standard__qiskit_standard__wisq_rules', 'square_heisenberg_N9__qiskit_standard__qiskit_standard__wisq_bqskit', 'square_heisenberg_N9__qiskit_standard__qiskit_standard__tket', 'square_heisenberg_N9__qiskit_standard__qiskit_standard__qiskit_ai', 'square_heisenberg_N9__qiskit_standard__qiskit_standard__qiskit_standard']

In [118]:
# All original Circuits that had no Optimization done
missing_circuits  = list(set(og_circuits) - set(og_circuits_master))

missing_circuits

['teleportv2', 'inverseqft1', 'qec', 'teleport', 'inverseqft2']

In [119]:
##All missing chains
missing_chains = list(set(all_possible_chains) - set(unique_opt_chains))

In [120]:
# Number of missing chains for each chain length
missing_one = 0
missing_two = 0
missing_three = 0
for string in missing_chains:
    split = string.split("__")
    if len(split) == 4:
        missing_three += 1
    elif len(split) == 3:
        missing_two += 1
    elif len(split) == 2:
        missing_one += 1

print(f"Missing one optimizer chains: {missing_one}")
print(f"Missing two optimizer chains: {missing_two}")
print(f"Missing three optimizer chains: {missing_three}")

Missing one optimizer chains: 43
Missing two optimizer chains: 287
Missing three optimizer chains: 9970

In [128]:
master_df.to_csv("master.csv", index=False)

In [122]:
import os
print(os.getcwd())

/Users/andrewweiland/UCCS_REU

In [123]:
master_df

,id,parent_circuit_id,chain_name,original_circuit,original_circuit_path,opt_1,opt_2,opt_3,qasm_path,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,opt_chain
0,1,1,single_1,efficient_su2_10_r2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,NaN,NaN,NaN,10,17,18,78,0,23,18,138,efficient_su2_10_r2__wisq_rules
1,2,1,single_1,efficient_su2_10_r2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,NaN,NaN,NaN,10,17,18,78,0,23,18,138,efficient_su2_10_r2__wisq_rules
2,3,1,single_2,efficient_su2_10_r2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,NaN,NaN,NaN,10,17,18,78,0,45,13,73,efficient_su2_10_r2__wisq_bqskit
3,4,1,single_2,efficient_su2_10_r2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,NaN,NaN,NaN,10,17,18,78,0,34,12,59,efficient_su2_10_r2__wisq_bqskit
4,5,1,single_2,efficient_su2_10_r2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,NaN,NaN,NaN,10,17,18,78,0,27,12,45,efficient_su2_10_r2__wisq_bqskit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16554,16555,1266,chain3_wisq_rules__wisq_bqskit__wisq_bqskit,mod5_4,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,wisq_rules,wisq_bqskit,wisq_bqskit,NaN,5,23,4,23,0,71,18,127,mod5_4__wisq_rules__wisq_bqskit__wisq_bqskit
16555,16556,1266,chain3_wisq_rules__wisq_bqskit__wisq_rules,mod5_4,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,wisq_rules,wisq_bqskit,wisq_rules,NaN,5,23,4,23,0,83,18,133,mod5_4__wisq_rules__wisq_bqskit__wisq_rules
16556,16557,1267,chain3_wisq_rules__wisq_rules__qiskit_ai,mod5_4,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,wisq_rules,wisq_rules,qiskit_ai,NaN,5,23,4,23,0,77,37,94,mod5_4__wisq_rules__wisq_rules__qiskit_ai
16557,16558,1267,chain3_wisq_rules__wisq_rules__qiskit_standard,mod5_4,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,wisq_rules,wisq_rules,qiskit_standard,NaN,5,23,4,23,0,90,51,128,mod5_4__wisq_rules__wisq_rules__qiskit_standard
16558,16559,1267,chain3_wisq_rules__wisq_rules__tket,mod5_4,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,wisq_rules,wisq_rules,tket,NaN,5,23,4,23,0,38,21,49,mod5_4__wisq_rules__wisq_rules__tket