In [77]:
import json

with open("/Users/andrewweiland/UCCS_REU/quantum-optimizer-orchestration/brute_force_chains/cheap_optimizers/full_run/one_opt/results_20260610_124820.json") as f:
    data = json.load(f)

print(type(data))

<class 'dict'>

In [85]:
with open("/Users/andrewweiland/UCCS_REU/quantum-optimizer-orchestration/brute_force_chains/cheap_optimizers/full_run/one_opt_qiskit_ai/reports/results_20260611_102356.json") as f:
    qiskit_ai_data = json.load(f)
qiskit_ai_df = pd.DataFrame(qiskit_ai_data["results"])
qiskit_ai_df[qiskit_ai_df["circuit"] == "qft_N002"].iloc[0]["metrics"]

{'depth': 11, 'two_qubit_gates': 3, 'two_qubit_depth': 3, 'total_gates': 17}

In [86]:
df = pd.DataFrame(data["results"])
df[df["circuit"] == "qft_N013"].iloc[0]["metrics"]

{'depth': 302,
 'two_qubit_gates': 174,
 'two_qubit_depth': 123,
 'total_gates': 538}

In [70]:
import pandas as pd
df = pd.DataFrame(data["results"])
df = df[df["runner"] != "qiskit_ai"]

In [71]:
df

,circuit,runner,optimizer,label,metrics,metadata,artifact_path
1,efficient_su2_10_r2,qiskit_standard,chain,chain_qiskit_standard,"{'depth': 11, 'two_qubit_gates': 18, 'two_qubi...",{'chain_name': 'cheap_1_opt_efficient_su2_10_r...,brute_force_chains/cheap_optimizers/full_run/o...
2,efficient_su2_10_r2,tket,chain,chain_tket,"{'depth': 11, 'two_qubit_gates': 18, 'two_qubi...",{'chain_name': 'cheap_1_opt_efficient_su2_10_r...,brute_force_chains/cheap_optimizers/full_run/o...
4,efficient_su2_12,qiskit_standard,chain,chain_qiskit_standard,"{'depth': 29, 'two_qubit_gates': 66, 'two_qubi...",{'chain_name': 'cheap_1_opt_efficient_su2_12_q...,brute_force_chains/cheap_optimizers/full_run/o...
5,efficient_su2_12,tket,chain,chain_tket,"{'depth': 29, 'two_qubit_gates': 66, 'two_qubi...",{'chain_name': 'cheap_1_opt_efficient_su2_12_t...,brute_force_chains/cheap_optimizers/full_run/o...
7,efficient_su2_12_r2,qiskit_standard,chain,chain_qiskit_standard,"{'depth': 13, 'two_qubit_gates': 22, 'two_qubi...",{'chain_name': 'cheap_1_opt_efficient_su2_12_r...,brute_force_chains/cheap_optimizers/full_run/o...
...,...,...,...,...,...,...,...
316,square_heisenberg_N16,tket,chain,chain_tket,"{'depth': 113, 'two_qubit_gates': 72, 'two_qub...",{'chain_name': 'cheap_1_opt_square_heisenberg_...,brute_force_chains/cheap_optimizers/full_run/o...
318,square_heisenberg_N4,qiskit_standard,chain,chain_qiskit_standard,"{'depth': 35, 'two_qubit_gates': 12, 'two_qubi...",{'chain_name': 'cheap_1_opt_square_heisenberg_...,brute_force_chains/cheap_optimizers/full_run/o...
319,square_heisenberg_N4,tket,chain,chain_tket,"{'depth': 40, 'two_qubit_gates': 12, 'two_qubi...",{'chain_name': 'cheap_1_opt_square_heisenberg_...,brute_force_chains/cheap_optimizers/full_run/o...
321,square_heisenberg_N9,qiskit_standard,chain,chain_qiskit_standard,"{'depth': 69, 'two_qubit_gates': 36, 'two_qubi...",{'chain_name': 'cheap_1_opt_square_heisenberg_...,brute_force_chains/cheap_optimizers/full_run/o...
322,square_heisenberg_N9,tket,chain,chain_tket,"{'depth': 78, 'two_qubit_gates': 36, 'two_qubi...",{'chain_name': 'cheap_1_opt_square_heisenberg_...,brute_force_chains/cheap_optimizers/full_run/o...

In [72]:
with open("/Users/andrewweiland/UCCS_REU/quantum-optimizer-orchestration/brute_force_chains/cheap_optimizers/full_run/one_opt_qiskit_ai/reports/results_20260611_102356.json") as f:
    qiskit_ai_data = json.load(f)
qiskit_ai_df = pd.DataFrame(qiskit_ai_data["results"])
df = pd.concat([df, qiskit_ai_df], ignore_index=True)
df

,circuit,runner,optimizer,label,metrics,metadata,artifact_path
0,efficient_su2_10_r2,qiskit_standard,chain,chain_qiskit_standard,"{'depth': 11, 'two_qubit_gates': 18, 'two_qubi...",{'chain_name': 'cheap_1_opt_efficient_su2_10_r...,brute_force_chains/cheap_optimizers/full_run/o...
1,efficient_su2_10_r2,tket,chain,chain_tket,"{'depth': 11, 'two_qubit_gates': 18, 'two_qubi...",{'chain_name': 'cheap_1_opt_efficient_su2_10_r...,brute_force_chains/cheap_optimizers/full_run/o...
2,efficient_su2_12,qiskit_standard,chain,chain_qiskit_standard,"{'depth': 29, 'two_qubit_gates': 66, 'two_qubi...",{'chain_name': 'cheap_1_opt_efficient_su2_12_q...,brute_force_chains/cheap_optimizers/full_run/o...
3,efficient_su2_12,tket,chain,chain_tket,"{'depth': 29, 'two_qubit_gates': 66, 'two_qubi...",{'chain_name': 'cheap_1_opt_efficient_su2_12_t...,brute_force_chains/cheap_optimizers/full_run/o...
4,efficient_su2_12_r2,qiskit_standard,chain,chain_qiskit_standard,"{'depth': 13, 'two_qubit_gates': 22, 'two_qubi...",{'chain_name': 'cheap_1_opt_efficient_su2_12_r...,brute_force_chains/cheap_optimizers/full_run/o...
...,...,...,...,...,...,...,...
316,real_amplitudes_8,qiskit_ai,chain,chain_qiskit_ai,"{'depth': 27, 'two_qubit_gates': 21, 'two_qubi...",{'chain_name': 'one_opt_qiskit_ai_real_amplitu...,brute_force_chains/cheap_optimizers/full_run/o...
317,real_amplitudes_8_r2,qiskit_ai,chain,chain_qiskit_ai,"{'depth': 9, 'two_qubit_gates': 14, 'two_qubit...",{'chain_name': 'one_opt_qiskit_ai_real_amplitu...,brute_force_chains/cheap_optimizers/full_run/o...
318,square_heisenberg_N16,qiskit_ai,chain,chain_qiskit_ai,"{'depth': 106, 'two_qubit_gates': 72, 'two_qub...",{'chain_name': 'one_opt_qiskit_ai_square_heise...,brute_force_chains/cheap_optimizers/full_run/o...
319,square_heisenberg_N4,qiskit_ai,chain,chain_qiskit_ai,"{'depth': 35, 'two_qubit_gates': 12, 'two_qubi...",{'chain_name': 'one_opt_qiskit_ai_square_heise...,brute_force_chains/cheap_optimizers/full_run/o...
320,square_heisenberg_N9,qiskit_ai,chain,chain_qiskit_ai,"{'depth': 71, 'two_qubit_gates': 36, 'two_qubi...",{'chain_name': 'one_opt_qiskit_ai_square_heise...,brute_force_chains/cheap_optimizers/full_run/o...

In [73]:
df["opt_level"] = df["metadata"].apply(lambda x: x.get("num_steps"))
df["opt_1"] = df["metadata"].apply(
    lambda x: x["steps"][0]["name"] if len(x["steps"]) > 0 else pd.NA
)
df["opt_2"] = df["metadata"].apply(
    lambda x: x["steps"][1]["name"] if len(x["steps"]) > 1 else pd.NA
)
df["opt_3"] = df["metadata"].apply(
    lambda x: x["steps"][2]["name"] if len(x["steps"]) > 2 else pd.NA
)
df["opt_chain"] = df.apply(
    lambda row: "__".join(
        [str(x) for x in [
            row["circuit"],
            row["opt_1"],
            row["opt_2"],
            row["opt_3"]
        ] if pd.notna(x)]
    ),
    axis=1
)
df["runtime"] = df["metadata"].apply(lambda x: x.get("total_duration_seconds"))
df["final_depth"] = df["metrics"].apply(lambda x: x.get("depth"))
df["final_two_qubit_gate_count"] = df["metrics"].apply(lambda x: x.get("two_qubit_gates"))
df["final_two_qubit_depth"] = df["metrics"].apply(lambda x: x.get("two_qubit_depth"))
df["final_total_gates"] = df["metrics"].apply(lambda x: x.get("total_gates"))
df.drop(columns=["metadata", "metrics", "runner", "label", ], inplace=True)
df.head()

,circuit,optimizer,artifact_path,opt_level,opt_1,opt_2,opt_3,opt_chain,runtime,final_depth,final_two_qubit_gate_count,final_two_qubit_depth,final_total_gates
0,efficient_su2_10_r2,chain,brute_force_chains/cheap_optimizers/full_run/o...,1,qiskit_standard,<NA>,<NA>,efficient_su2_10_r2__qiskit_standard,0.008640,11,18,11,18
1,efficient_su2_10_r2,chain,brute_force_chains/cheap_optimizers/full_run/o...,1,tket,<NA>,<NA>,efficient_su2_10_r2__tket,0.590575,11,18,11,18
2,efficient_su2_12,chain,brute_force_chains/cheap_optimizers/full_run/o...,1,qiskit_standard,<NA>,<NA>,efficient_su2_12__qiskit_standard,0.221234,29,66,21,162
3,efficient_su2_12,chain,brute_force_chains/cheap_optimizers/full_run/o...,1,tket,<NA>,<NA>,efficient_su2_12__tket,1.049814,29,66,21,162
4,efficient_su2_12_r2,chain,brute_force_chains/cheap_optimizers/full_run/o...,1,qiskit_standard,<NA>,<NA>,efficient_su2_12_r2__qiskit_standard,0.005118,13,22,13,22

In [74]:
circuits = pd.read_csv("/Users/andrewweiland/UCCS_REU/quantum-optimizer-orchestration/dataset_analysis/circuits.csv")
circuits.head()

,Unnamed: 0,id,name,category,source,qasm_path,num_qubits,initial_depth,initial_two_qubit_gates,initial_two_qubit_depth,initial_total_gates,gate_density,two_qubit_ratio,created_at,optimizer_chain,original_circuit
0,0,1,efficient_su2_10_r2,efficient_su2,local,benchmarks/ai_transpile/qasm/efficient_su2_10_...,10,17,18,11,78,7.800000,0.230769,2026-03-05 20:39:31,NaN,efficient_su2_10_r2
1,1,2,efficient_su2_12,efficient_su2,local,benchmarks/ai_transpile/qasm/efficient_su2_12....,12,25,66,21,114,9.500000,0.578947,2026-03-05 20:39:31,NaN,efficient_su2_12
2,2,3,efficient_su2_12_r2,efficient_su2,local,benchmarks/ai_transpile/qasm/efficient_su2_12_...,12,19,22,13,94,7.833333,0.234043,2026-03-05 20:39:31,NaN,efficient_su2_12_r2
3,3,4,efficient_su2_16,efficient_su2,local,benchmarks/ai_transpile/qasm/efficient_su2_16....,16,33,120,29,184,11.500000,0.652174,2026-03-05 20:39:31,NaN,efficient_su2_16
4,4,5,efficient_su2_8,efficient_su2,local,benchmarks/ai_transpile/qasm/efficient_su2_8.qasm,8,27,56,21,104,13.000000,0.538462,2026-03-05 20:39:31,NaN,efficient_su2_8

In [75]:
df["parent_circuit_id"] = df["circuit"].map(
    circuits.set_index("name")["id"]
)
df.head()
df["parent_circuit"] = df["circuit"]
df["original_circuit_id"] = df["circuit"].map(
    circuits.set_index("name")["id"]
)
df["original_circuit"] = df["circuit"]
df["original_category"] = df["circuit"].map(
    circuits.set_index("name")["category"]
)
df["original_circuit_path"] = df["circuit"].map(
    circuits.set_index("name")["qasm_path"]
)

df["chain_name"] = df.apply(
    lambda row: "__".join(
        [str(x) for x in [
            row["opt_1"],
            row["opt_2"],
            row["opt_3"]
        ] if pd.notna(x)]
    ),
    axis=1
)

df["initial_num_qubits"] = df["circuit"].map(
    circuits.set_index("name")["num_qubits"]
)
df["initial_depth"] = df["circuit"].map(
    circuits.set_index("name")["initial_depth"]
)
df["initial_two_qubit_gates"] = df["circuit"].map(
    circuits.set_index("name")["initial_two_qubit_gates"]
)
df["initial_total_gates"] = df["circuit"].map(
    circuits.set_index("name")["initial_total_gates"]
)
df["final_num_qubits"] = df["initial_num_qubits"]

df = df[
    [
        "parent_circuit_id",
        "parent_circuit",
        "original_circuit_id",
        "original_circuit",
        "original_category",
        "original_circuit_path",
        "chain_name",
        "opt_level",
        "opt_1",
        "opt_2",
        "opt_3",
        "artifact_path",
        "initial_num_qubits",
        "initial_depth",
        "initial_two_qubit_gates",
        "initial_total_gates",
        "final_num_qubits",
        "final_depth",
        "final_two_qubit_gate_count",
        "final_total_gates",
        "runtime",
        "opt_chain"
    ]
]

df.head()

,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,opt_2,opt_3,artifact_path,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gate_count,final_total_gates,runtime,opt_chain
0,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_standard,1,qiskit_standard,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,10,17,18,78,10,11,18,18,0.008640,efficient_su2_10_r2__qiskit_standard
1,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,tket,1,tket,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,10,17,18,78,10,11,18,18,0.590575,efficient_su2_10_r2__tket
2,2,efficient_su2_12,2,efficient_su2_12,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12....,qiskit_standard,1,qiskit_standard,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,12,25,66,114,12,29,66,162,0.221234,efficient_su2_12__qiskit_standard
3,2,efficient_su2_12,2,efficient_su2_12,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12....,tket,1,tket,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,12,25,66,114,12,29,66,162,1.049814,efficient_su2_12__tket
4,3,efficient_su2_12_r2,3,efficient_su2_12_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12_...,qiskit_standard,1,qiskit_standard,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,12,19,22,94,12,13,22,22,0.005118,efficient_su2_12_r2__qiskit_standard

In [76]:
df.to_csv("cheap_single_opts.csv", index=False)

In [56]:
pd.set_option("display.max_columns", None)
all_possible_chains = pd.read_csv("/Users/andrewweiland/UCCS_REU/quantum-optimizer-orchestration/dataset_analysis/all_possible_chains.csv")
all_possible_chains.head()

,id,opt_chain,parent_circuit_id,parent_circuit,parent_path,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,opt_2,opt_3,artifact_path,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds
0,0,efficient_su2_10_r2__qiskit_ai,1,efficient_su2_10_r2,NaN,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,NaN,1,qiskit_ai,NaN,NaN,NaN,10,17,18,78,0,0,0,0,0.0
1,1,efficient_su2_10_r2__qiskit_standard,1,efficient_su2_10_r2,NaN,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,NaN,1,qiskit_standard,NaN,NaN,NaN,10,17,18,78,0,0,0,0,0.0
2,2,efficient_su2_10_r2__tket,1,efficient_su2_10_r2,NaN,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,NaN,1,tket,NaN,NaN,NaN,10,17,18,78,0,0,0,0,0.0
3,3,efficient_su2_10_r2__wisq_rules,1,efficient_su2_10_r2,NaN,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,NaN,1,wisq_rules,NaN,NaN,NaN,10,17,18,78,0,0,0,0,0.0
4,4,efficient_su2_10_r2__wisq_bqskit,1,efficient_su2_10_r2,NaN,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,NaN,1,wisq_bqskit,NaN,NaN,NaN,10,17,18,78,0,0,0,0,0.0

In [57]:
df

,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,opt_2,opt_3,artifact_path,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gate_count,final_total_gates,runtime,opt_chain
0,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_standard,1,qiskit_standard,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,10,17,18,78,10,11,18,18,0.008640,efficient_su2_10_r2__qiskit_standard
1,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,tket,1,tket,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,10,17,18,78,10,11,18,18,0.590575,efficient_su2_10_r2__tket
2,2,efficient_su2_12,2,efficient_su2_12,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12....,qiskit_standard,1,qiskit_standard,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,12,25,66,114,12,29,66,162,0.221234,efficient_su2_12__qiskit_standard
3,2,efficient_su2_12,2,efficient_su2_12,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12....,tket,1,tket,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,12,25,66,114,12,29,66,162,1.049814,efficient_su2_12__tket
4,3,efficient_su2_12_r2,3,efficient_su2_12_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12_...,qiskit_standard,1,qiskit_standard,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,12,19,22,94,12,13,22,22,0.005118,efficient_su2_12_r2__qiskit_standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,107,real_amplitudes_8,107,real_amplitudes_8,real_amplitudes,benchmarks/ai_transpile/qasm/real_amplitudes_8...,qiskit_ai,1,qiskit_ai,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,8,15,21,53,8,27,21,149,0.018989,real_amplitudes_8__qiskit_ai
419,108,real_amplitudes_8_r2,108,real_amplitudes_8_r2,real_amplitudes,benchmarks/ai_transpile/qasm/real_amplitudes_8...,qiskit_ai,1,qiskit_ai,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,8,12,14,38,8,9,14,14,0.005857,real_amplitudes_8_r2__qiskit_ai
420,109,square_heisenberg_N16,109,square_heisenberg_N16,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,qiskit_ai,1,qiskit_ai,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,16,361,288,1024,16,106,72,333,0.053761,square_heisenberg_N16__qiskit_ai
421,110,square_heisenberg_N4,110,square_heisenberg_N4,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,qiskit_ai,1,qiskit_ai,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,4,121,48,172,4,35,12,57,0.008413,square_heisenberg_N4__qiskit_ai
422,111,square_heisenberg_N9,111,square_heisenberg_N9,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,qiskit_ai,1,qiskit_ai,<NA>,<NA>,brute_force_chains/cheap_optimizers/full_run/o...,9,241,144,513,9,71,36,168,0.021392,square_heisenberg_N9__qiskit_ai

In [58]:
two_opts = all_possible_chains[all_possible_chains["opt_level"] == 2].copy()
two_opts["parent_path"] = two_opts["parent_circuit"].map(
    df.set_index("opt_chain")["artifact_path"]
)
two_opts

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [41]:
two_opts[two_opts["parent_path"].notna()]

,id,opt_chain,parent_circuit_id,parent_circuit,parent_path,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,opt_2,opt_3,artifact_path,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds
5,5,efficient_su2_10_r2__qiskit_ai__qiskit_ai,0,efficient_su2_10_r2__qiskit_ai,brute_force_chains/cheap_optimizers/full_run/o...,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,NaN,2,qiskit_ai,qiskit_ai,NaN,NaN,10,17,18,78,0,0,0,0,0.0
6,6,efficient_su2_10_r2__qiskit_ai__qiskit_standard,0,efficient_su2_10_r2__qiskit_ai,brute_force_chains/cheap_optimizers/full_run/o...,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,NaN,2,qiskit_ai,qiskit_standard,NaN,NaN,10,17,18,78,0,0,0,0,0.0
7,7,efficient_su2_10_r2__qiskit_ai__tket,0,efficient_su2_10_r2__qiskit_ai,brute_force_chains/cheap_optimizers/full_run/o...,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,NaN,2,qiskit_ai,tket,NaN,NaN,10,17,18,78,0,0,0,0,0.0
8,8,efficient_su2_10_r2__qiskit_ai__wisq_rules,0,efficient_su2_10_r2__qiskit_ai,brute_force_chains/cheap_optimizers/full_run/o...,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,NaN,2,qiskit_ai,wisq_rules,NaN,NaN,10,17,18,78,0,0,0,0,0.0
9,9,efficient_su2_10_r2__qiskit_ai__wisq_bqskit,0,efficient_su2_10_r2__qiskit_ai,brute_force_chains/cheap_optimizers/full_run/o...,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,NaN,2,qiskit_ai,wisq_bqskit,NaN,NaN,10,17,18,78,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17065,17065,square_heisenberg_N9__tket__qiskit_ai,17052,square_heisenberg_N9__tket,brute_force_chains/cheap_optimizers/full_run/o...,111,square_heisenberg_N9,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,NaN,2,tket,qiskit_ai,NaN,NaN,9,241,144,513,0,0,0,0,0.0
17066,17066,square_heisenberg_N9__tket__qiskit_standard,17052,square_heisenberg_N9__tket,brute_force_chains/cheap_optimizers/full_run/o...,111,square_heisenberg_N9,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,NaN,2,tket,qiskit_standard,NaN,NaN,9,241,144,513,0,0,0,0,0.0
17067,17067,square_heisenberg_N9__tket__tket,17052,square_heisenberg_N9__tket,brute_force_chains/cheap_optimizers/full_run/o...,111,square_heisenberg_N9,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,NaN,2,tket,tket,NaN,NaN,9,241,144,513,0,0,0,0,0.0
17068,17068,square_heisenberg_N9__tket__wisq_rules,17052,square_heisenberg_N9__tket,brute_force_chains/cheap_optimizers/full_run/o...,111,square_heisenberg_N9,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,NaN,2,tket,wisq_rules,NaN,NaN,9,241,144,513,0,0,0,0,0.0
17069,17069,square_heisenberg_N9__tket__wisq_bqskit,17052,square_heisenberg_N9__tket,brute_force_chains/cheap_optimizers/full_run/o...,111,square_heisenberg_N9,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,NaN,2,tket,wisq_bqskit,NaN,NaN,9,241,144,513,0,0,0,0,0.0