In [13]:
import pandas as pd

In [14]:
master_df = pd.read_csv("master.csv")
master_df

,id,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,...,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds,opt_chain
0,1,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,1,wisq_rules,...,10,17,18,78,0,23,18,138,600.292814,efficient_su2_10_r2__wisq_rules
1,2,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,1,wisq_rules,...,10,17,18,78,0,23,18,138,600.192577,efficient_su2_10_r2__wisq_rules
2,3,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,45,13,73,402.726940,efficient_su2_10_r2__wisq_bqskit
3,4,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,34,12,59,422.451553,efficient_su2_10_r2__wisq_bqskit
4,5,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,27,12,45,540.983333,efficient_su2_10_r2__wisq_bqskit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16554,16555,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__wisq_bqskit,3,wisq_rules,...,5,23,4,23,0,71,18,127,1202.415318,mod5_4__wisq_rules__wisq_bqskit__wisq_bqskit
16555,16556,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__wisq_rules,3,wisq_rules,...,5,23,4,23,0,83,18,133,1501.703982,mod5_4__wisq_rules__wisq_bqskit__wisq_rules
16556,16557,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__qiskit_ai,3,wisq_rules,...,5,23,4,23,0,77,37,94,1201.578077,mod5_4__wisq_rules__wisq_rules__qiskit_ai
16557,16558,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__qiskit_standard,3,wisq_rules,...,5,23,4,23,0,90,51,128,1201.367918,mod5_4__wisq_rules__wisq_rules__qiskit_standard
16558,16559,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__tket,3,wisq_rules,...,5,23,4,23,0,38,21,49,1201.609071,mod5_4__wisq_rules__wisq_rules__tket

In [15]:
# Usable Data
# Includes data that only used wisq_rules, wisq_bqskit, and tket
# These methods did not use hardware-awaredness

usable_df = master_df[~master_df["chain_name"].str.contains("qiskit", na=False)].reset_index(drop=True)
usable_df

,id,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,...,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds,opt_chain
0,1,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,1,wisq_rules,...,10,17,18,78,0,23,18,138,600.292814,efficient_su2_10_r2__wisq_rules
1,2,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,1,wisq_rules,...,10,17,18,78,0,23,18,138,600.192577,efficient_su2_10_r2__wisq_rules
2,3,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,45,13,73,402.726940,efficient_su2_10_r2__wisq_bqskit
3,4,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,34,12,59,422.451553,efficient_su2_10_r2__wisq_bqskit
4,5,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,27,12,45,540.983333,efficient_su2_10_r2__wisq_bqskit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6193,16551,1263,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__tket__wisq_rules,3,wisq_rules,...,5,23,4,23,0,33,19,44,1201.396497,mod5_4__wisq_rules__tket__wisq_rules
6194,16554,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__tket,3,wisq_rules,...,5,23,4,23,0,77,18,119,903.127520,mod5_4__wisq_rules__wisq_bqskit__tket
6195,16555,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__wisq_bqskit,3,wisq_rules,...,5,23,4,23,0,71,18,127,1202.415318,mod5_4__wisq_rules__wisq_bqskit__wisq_bqskit
6196,16556,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__wisq_rules,3,wisq_rules,...,5,23,4,23,0,83,18,133,1501.703982,mod5_4__wisq_rules__wisq_bqskit__wisq_rules
6197,16559,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__tket,3,wisq_rules,...,5,23,4,23,0,38,21,49,1201.609071,mod5_4__wisq_rules__wisq_rules__tket

In [17]:
usable_one_opt = usable_df[usable_df["opt_level"] == 1].reset_index(drop=True)
usable_one_opt

,id,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,...,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds,opt_chain
0,1,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,1,wisq_rules,...,10,17,18,78,0,23,18,138,600.292814,efficient_su2_10_r2__wisq_rules
1,2,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,1,wisq_rules,...,10,17,18,78,0,23,18,138,600.192577,efficient_su2_10_r2__wisq_rules
2,3,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,45,13,73,402.726940,efficient_su2_10_r2__wisq_bqskit
3,4,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,34,12,59,422.451553,efficient_su2_10_r2__wisq_bqskit
4,5,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,27,12,45,540.983333,efficient_su2_10_r2__wisq_bqskit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,1441,111,square_heisenberg_N9,111,square_heisenberg_N9,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,wisq_bqskit,1,wisq_bqskit,...,9,241,144,513,0,114,36,285,301.442531,square_heisenberg_N9__wisq_bqskit
796,1442,111,square_heisenberg_N9,111,square_heisenberg_N9,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,wisq_bqskit,1,wisq_bqskit,...,9,241,144,513,0,113,36,291,301.357553,square_heisenberg_N9__wisq_bqskit
797,1443,111,square_heisenberg_N9,111,square_heisenberg_N9,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,tket,1,tket,...,9,241,144,513,0,77,36,193,2.114933,square_heisenberg_N9__tket
798,1444,111,square_heisenberg_N9,111,square_heisenberg_N9,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,tket,1,tket,...,9,241,144,513,0,77,36,193,1.984467,square_heisenberg_N9__tket
799,1445,111,square_heisenberg_N9,111,square_heisenberg_N9,square-heisenberg,benchmarks/ai_transpile/qasm/square-heisenberg...,tket,1,tket,...,9,241,144,513,0,77,36,193,1.776483,square_heisenberg_N9__tket

In [21]:
duplicates = usable_df[usable_df.duplicated(subset=["opt_chain"], keep=False)]
duplicates

,id,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,...,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds,opt_chain
0,1,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,1,wisq_rules,...,10,17,18,78,0,23,18,138,600.292814,efficient_su2_10_r2__wisq_rules
1,2,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,1,wisq_rules,...,10,17,18,78,0,23,18,138,600.192577,efficient_su2_10_r2__wisq_rules
2,3,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,45,13,73,402.726940,efficient_su2_10_r2__wisq_bqskit
3,4,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,34,12,59,422.451553,efficient_su2_10_r2__wisq_bqskit
4,5,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,27,12,45,540.983333,efficient_su2_10_r2__wisq_bqskit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5736,14436,1427,artifact_vbe_adder_3__wisq_rules,43,vbe_adder_3,feynman,benchmarks/ai_transpile/qasm/feynman/vbe_adder...,chain_wisq_bqskit__wisq_bqskit,2,wisq_bqskit,...,10,28,10,50,0,123,36,261,602.623133,vbe_adder_3__wisq_bqskit__wisq_bqskit
5737,14437,1427,artifact_vbe_adder_3__wisq_rules,43,vbe_adder_3,feynman,benchmarks/ai_transpile/qasm/feynman/vbe_adder...,chain_wisq_bqskit__wisq_rules,2,wisq_bqskit,...,10,28,10,50,0,133,38,252,901.790689,vbe_adder_3__wisq_bqskit__wisq_rules
5738,14440,1428,artifact_vbe_adder_3__wisq_rules,43,vbe_adder_3,feynman,benchmarks/ai_transpile/qasm/feynman/vbe_adder...,chain_wisq_rules__tket,2,wisq_rules,...,10,28,10,50,0,62,41,104,601.736419,vbe_adder_3__wisq_rules__tket
5739,14441,1428,artifact_vbe_adder_3__wisq_rules,43,vbe_adder_3,feynman,benchmarks/ai_transpile/qasm/feynman/vbe_adder...,chain_wisq_rules__wisq_bqskit,2,wisq_rules,...,10,28,10,50,0,118,36,292,900.847755,vbe_adder_3__wisq_rules__wisq_bqskit
5740,14442,1428,artifact_vbe_adder_3__wisq_rules,43,vbe_adder_3,feynman,benchmarks/ai_transpile/qasm/feynman/vbe_adder...,chain_wisq_rules__wisq_rules,2,wisq_rules,...,10,28,10,50,0,90,42,153,1200.070453,vbe_adder_3__wisq_rules__wisq_rules

In [22]:
non_duplicates = usable_df[~usable_df.duplicated(subset=["opt_chain"], keep=False)].reset_index(drop=True)
non_duplicates

,id,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,...,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds,opt_chain
0,457,21,hwb10,21,hwb10,feynman,benchmarks/ai_transpile/qasm/feynman/hwb10.qasm,tket,1,tket,...,16,18050,9508,31764,0,43350,31215,72583,668.369335,hwb10__tket
1,465,22,hwb11,22,hwb11,feynman,benchmarks/ai_transpile/qasm/feynman/hwb11.qasm,tket,1,tket,...,15,52290,25855,87789,0,126166,89925,203236,2319.558573,hwb11__tket
2,473,23,hwb12,23,hwb12,feynman,benchmarks/ai_transpile/qasm/feynman/hwb12.qasm,tket,1,tket,...,20,98611,44833,171482,0,251679,177592,405572,6020.482178,hwb12__tket
3,876,62,qft_10,62,qft_10,qft,benchmarks/ai_transpile/qasm/qft_10.qasm,wisq_rules,1,wisq_rules,...,10,74,105,250,0,205,103,732,600.242546,qft_10__wisq_rules
4,877,62,qft_10,62,qft_10,qft,benchmarks/ai_transpile/qasm/qft_10.qasm,wisq_bqskit,1,wisq_bqskit,...,10,74,105,250,0,275,102,625,301.561956,qft_10__wisq_bqskit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,16551,1263,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__tket__wisq_rules,3,wisq_rules,...,5,23,4,23,0,33,19,44,1201.396497,mod5_4__wisq_rules__tket__wisq_rules
594,16554,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__tket,3,wisq_rules,...,5,23,4,23,0,77,18,119,903.127520,mod5_4__wisq_rules__wisq_bqskit__tket
595,16555,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__wisq_bqskit,3,wisq_rules,...,5,23,4,23,0,71,18,127,1202.415318,mod5_4__wisq_rules__wisq_bqskit__wisq_bqskit
596,16556,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__wisq_rules,3,wisq_rules,...,5,23,4,23,0,83,18,133,1501.703982,mod5_4__wisq_rules__wisq_bqskit__wisq_rules
597,16559,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__tket,3,wisq_rules,...,5,23,4,23,0,38,21,49,1201.609071,mod5_4__wisq_rules__wisq_rules__tket

In [25]:
conflicting = usable_df.groupby("opt_chain").filter(
    lambda g: (
        g["final_depth"].nunique() > 1
        or g["final_two_qubit_gates"].nunique() > 1
        or g["final_total_gates"].nunique() > 1
    )
)
conflicting

,id,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,...,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds,opt_chain
2,3,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,45,13,73,402.726940,efficient_su2_10_r2__wisq_bqskit
3,4,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,34,12,59,422.451553,efficient_su2_10_r2__wisq_bqskit
4,5,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_bqskit,1,wisq_bqskit,...,10,17,18,78,0,27,12,45,540.983333,efficient_su2_10_r2__wisq_bqskit
13,32,2,efficient_su2_12,2,efficient_su2_12,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12....,wisq_rules,1,wisq_rules,...,12,25,66,114,0,36,11,107,600.211930,efficient_su2_12__wisq_rules
14,33,2,efficient_su2_12,2,efficient_su2_12,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12....,wisq_rules,1,wisq_rules,...,12,25,66,114,0,32,11,107,600.204073,efficient_su2_12__wisq_rules
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5736,14436,1427,artifact_vbe_adder_3__wisq_rules,43,vbe_adder_3,feynman,benchmarks/ai_transpile/qasm/feynman/vbe_adder...,chain_wisq_bqskit__wisq_bqskit,2,wisq_bqskit,...,10,28,10,50,0,123,36,261,602.623133,vbe_adder_3__wisq_bqskit__wisq_bqskit
5737,14437,1427,artifact_vbe_adder_3__wisq_rules,43,vbe_adder_3,feynman,benchmarks/ai_transpile/qasm/feynman/vbe_adder...,chain_wisq_bqskit__wisq_rules,2,wisq_bqskit,...,10,28,10,50,0,133,38,252,901.790689,vbe_adder_3__wisq_bqskit__wisq_rules
5738,14440,1428,artifact_vbe_adder_3__wisq_rules,43,vbe_adder_3,feynman,benchmarks/ai_transpile/qasm/feynman/vbe_adder...,chain_wisq_rules__tket,2,wisq_rules,...,10,28,10,50,0,62,41,104,601.736419,vbe_adder_3__wisq_rules__tket
5739,14441,1428,artifact_vbe_adder_3__wisq_rules,43,vbe_adder_3,feynman,benchmarks/ai_transpile/qasm/feynman/vbe_adder...,chain_wisq_rules__wisq_bqskit,2,wisq_rules,...,10,28,10,50,0,118,36,292,900.847755,vbe_adder_3__wisq_rules__wisq_bqskit
5740,14442,1428,artifact_vbe_adder_3__wisq_rules,43,vbe_adder_3,feynman,benchmarks/ai_transpile/qasm/feynman/vbe_adder...,chain_wisq_rules__wisq_rules,2,wisq_rules,...,10,28,10,50,0,90,42,153,1200.070453,vbe_adder_3__wisq_rules__wisq_rules

In [27]:
clean_df = usable_df.groupby("opt_chain").filter(
    lambda g: (
        g["final_depth"].nunique() == 1
        and g["final_two_qubit_gates"].nunique() == 1
        and g["final_total_gates"].nunique() == 1
    )
)
clean_df

,id,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,...,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds,opt_chain
0,1,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,1,wisq_rules,...,10,17,18,78,0,23,18,138,600.292814,efficient_su2_10_r2__wisq_rules
1,2,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,1,wisq_rules,...,10,17,18,78,0,23,18,138,600.192577,efficient_su2_10_r2__wisq_rules
5,6,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,tket,1,tket,...,10,17,18,78,0,11,18,18,1.457696,efficient_su2_10_r2__tket
6,7,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,tket,1,tket,...,10,17,18,78,0,11,18,18,1.391856,efficient_su2_10_r2__tket
7,8,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,tket,1,tket,...,10,17,18,78,0,11,18,18,1.641361,efficient_su2_10_r2__tket
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6193,16551,1263,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__tket__wisq_rules,3,wisq_rules,...,5,23,4,23,0,33,19,44,1201.396497,mod5_4__wisq_rules__tket__wisq_rules
6194,16554,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__tket,3,wisq_rules,...,5,23,4,23,0,77,18,119,903.127520,mod5_4__wisq_rules__wisq_bqskit__tket
6195,16555,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__wisq_bqskit,3,wisq_rules,...,5,23,4,23,0,71,18,127,1202.415318,mod5_4__wisq_rules__wisq_bqskit__wisq_bqskit
6196,16556,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__wisq_rules,3,wisq_rules,...,5,23,4,23,0,83,18,133,1501.703982,mod5_4__wisq_rules__wisq_bqskit__wisq_rules
6197,16559,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__tket,3,wisq_rules,...,5,23,4,23,0,38,21,49,1201.609071,mod5_4__wisq_rules__wisq_rules__tket

In [29]:
# All chains that have already been run that were not duplicated
# And only contain wisq and tket optimization

unique_df = clean_df.drop_duplicates(
    subset=["opt_chain"],
    keep="first"
).reset_index(drop=True)
unique_df

,id,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,...,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds,opt_chain
0,1,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,wisq_rules,1,wisq_rules,...,10,17,18,78,0,23,18,138,600.292814,efficient_su2_10_r2__wisq_rules
1,6,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,tket,1,tket,...,10,17,18,78,0,11,18,18,1.457696,efficient_su2_10_r2__tket
2,36,2,efficient_su2_12,2,efficient_su2_12,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12....,tket,1,tket,...,12,25,66,114,0,29,66,162,2.179262,efficient_su2_12__tket
3,63,3,efficient_su2_12_r2,3,efficient_su2_12_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12_...,wisq_rules,1,wisq_rules,...,12,19,22,94,0,25,22,166,600.379808,efficient_su2_12_r2__wisq_rules
4,67,3,efficient_su2_12_r2,3,efficient_su2_12_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12_...,tket,1,tket,...,12,19,22,94,0,13,22,22,2.190790,efficient_su2_12_r2__tket
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,16551,1263,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__tket__wisq_rules,3,wisq_rules,...,5,23,4,23,0,33,19,44,1201.396497,mod5_4__wisq_rules__tket__wisq_rules
751,16554,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__tket,3,wisq_rules,...,5,23,4,23,0,77,18,119,903.127520,mod5_4__wisq_rules__wisq_bqskit__tket
752,16555,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__wisq_bqskit,3,wisq_rules,...,5,23,4,23,0,71,18,127,1202.415318,mod5_4__wisq_rules__wisq_bqskit__wisq_bqskit
753,16556,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__wisq_rules,3,wisq_rules,...,5,23,4,23,0,83,18,133,1501.703982,mod5_4__wisq_rules__wisq_bqskit__wisq_rules
754,16559,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__tket,3,wisq_rules,...,5,23,4,23,0,38,21,49,1201.609071,mod5_4__wisq_rules__wisq_rules__tket

In [30]:
unique_df.to_csv("usable_optimizer_only.csv", index=False)

In [32]:
hardware_df = master_df[master_df["chain_name"].str.contains("qiskit", na=False)].reset_index(drop=True)
hardware_df

,id,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,...,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds,opt_chain
0,14,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_ai,1,qiskit_ai,...,10,17,18,78,0,17,18,78,0.329484,efficient_su2_10_r2__qiskit_ai
1,15,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_ai,1,qiskit_ai,...,10,17,18,78,0,17,18,78,0.414190,efficient_su2_10_r2__qiskit_ai
2,16,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_ai,1,qiskit_ai,...,10,17,18,78,0,17,18,78,0.402045,efficient_su2_10_r2__qiskit_ai
3,17,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_ai,1,qiskit_ai,...,10,17,18,78,0,17,18,78,0.385018,efficient_su2_10_r2__qiskit_ai
4,18,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_ai,1,qiskit_ai,...,10,17,18,78,0,17,18,78,0.366843,efficient_su2_10_r2__qiskit_ai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10356,16548,1263,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__tket__qiskit_standard,3,wisq_rules,...,5,23,4,23,0,64,36,83,601.436214,mod5_4__wisq_rules__tket__qiskit_standard
10357,16552,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__qiskit_ai,3,wisq_rules,...,5,23,4,23,0,91,23,138,902.061189,mod5_4__wisq_rules__wisq_bqskit__qiskit_ai
10358,16553,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__qiskit_standard,3,wisq_rules,...,5,23,4,23,0,82,29,129,901.727071,mod5_4__wisq_rules__wisq_bqskit__qiskit_standard
10359,16557,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__qiskit_ai,3,wisq_rules,...,5,23,4,23,0,77,37,94,1201.578077,mod5_4__wisq_rules__wisq_rules__qiskit_ai
10360,16558,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__qiskit_standard,3,wisq_rules,...,5,23,4,23,0,90,51,128,1201.367918,mod5_4__wisq_rules__wisq_rules__qiskit_standard

In [33]:
clean_hardware = hardware_df.groupby("opt_chain").filter(
    lambda g: (
        g["final_depth"].nunique() == 1
        and g["final_two_qubit_gates"].nunique() == 1
        and g["final_total_gates"].nunique() == 1
    )
)
clean_hardware

,id,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,...,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds,opt_chain
0,14,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_ai,1,qiskit_ai,...,10,17,18,78,0,17,18,78,0.329484,efficient_su2_10_r2__qiskit_ai
1,15,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_ai,1,qiskit_ai,...,10,17,18,78,0,17,18,78,0.414190,efficient_su2_10_r2__qiskit_ai
2,16,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_ai,1,qiskit_ai,...,10,17,18,78,0,17,18,78,0.402045,efficient_su2_10_r2__qiskit_ai
3,17,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_ai,1,qiskit_ai,...,10,17,18,78,0,17,18,78,0.385018,efficient_su2_10_r2__qiskit_ai
4,18,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_ai,1,qiskit_ai,...,10,17,18,78,0,17,18,78,0.366843,efficient_su2_10_r2__qiskit_ai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10356,16548,1263,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__tket__qiskit_standard,3,wisq_rules,...,5,23,4,23,0,64,36,83,601.436214,mod5_4__wisq_rules__tket__qiskit_standard
10357,16552,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__qiskit_ai,3,wisq_rules,...,5,23,4,23,0,91,23,138,902.061189,mod5_4__wisq_rules__wisq_bqskit__qiskit_ai
10358,16553,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__qiskit_standard,3,wisq_rules,...,5,23,4,23,0,82,29,129,901.727071,mod5_4__wisq_rules__wisq_bqskit__qiskit_standard
10359,16557,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__qiskit_ai,3,wisq_rules,...,5,23,4,23,0,77,37,94,1201.578077,mod5_4__wisq_rules__wisq_rules__qiskit_ai
10360,16558,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__qiskit_standard,3,wisq_rules,...,5,23,4,23,0,90,51,128,1201.367918,mod5_4__wisq_rules__wisq_rules__qiskit_standard

In [34]:
# All chains that have already been run that were not duplicated
# which use hardware-aware qiskit optimizations

unique_hardware = clean_hardware.drop_duplicates(
    subset=["opt_chain"],
    keep="first"
).reset_index(drop=True)
unique_hardware

,id,parent_circuit_id,parent_circuit,original_circuit_id,original_circuit,original_category,original_circuit_path,chain_name,opt_level,opt_1,...,initial_num_qubits,initial_depth,initial_two_qubit_gates,initial_total_gates,final_num_qubits,final_depth,final_two_qubit_gates,final_total_gates,total_runtime_seconds,opt_chain
0,14,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_ai,1,qiskit_ai,...,10,17,18,78,0,17,18,78,0.329484,efficient_su2_10_r2__qiskit_ai
1,23,1,efficient_su2_10_r2,1,efficient_su2_10_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_10_...,qiskit_standard,1,qiskit_standard,...,10,17,18,78,0,11,18,18,0.967805,efficient_su2_10_r2__qiskit_standard
2,75,3,efficient_su2_12_r2,3,efficient_su2_12_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12_...,qiskit_ai,1,qiskit_ai,...,12,19,22,94,0,19,22,94,0.754238,efficient_su2_12_r2__qiskit_ai
3,84,3,efficient_su2_12_r2,3,efficient_su2_12_r2,efficient_su2,benchmarks/ai_transpile/qasm/efficient_su2_12_...,qiskit_standard,1,qiskit_standard,...,12,19,22,94,0,13,22,22,0.306156,efficient_su2_12_r2__qiskit_standard
4,156,6,W-state,6,W-state,feynman,benchmarks/ai_transpile/qasm/feynman/W-state.qasm,qiskit_ai,1,qiskit_ai,...,3,6,2,9,0,6,3,9,0.152223,W-state__qiskit_ai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,16548,1263,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__tket__qiskit_standard,3,wisq_rules,...,5,23,4,23,0,64,36,83,601.436214,mod5_4__wisq_rules__tket__qiskit_standard
1990,16552,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__qiskit_ai,3,wisq_rules,...,5,23,4,23,0,91,23,138,902.061189,mod5_4__wisq_rules__wisq_bqskit__qiskit_ai
1991,16553,1266,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_bqskit__qiskit_standard,3,wisq_rules,...,5,23,4,23,0,82,29,129,901.727071,mod5_4__wisq_rules__wisq_bqskit__qiskit_standard
1992,16557,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__qiskit_ai,3,wisq_rules,...,5,23,4,23,0,77,37,94,1201.578077,mod5_4__wisq_rules__wisq_rules__qiskit_ai
1993,16558,1267,mod5_4,28,mod5_4,feynman,benchmarks/ai_transpile/qasm/feynman/mod5_4.qasm,chain3_wisq_rules__wisq_rules__qiskit_standard,3,wisq_rules,...,5,23,4,23,0,90,51,128,1201.367918,mod5_4__wisq_rules__wisq_rules__qiskit_standard

In [35]:
unique_hardware.to_csv("usable_hardware_aware.csv", index=False)

In [39]:
circuit_df = pd.read_csv("circuits.csv")
circuit_df
local = circuit_df[circuit_df["source"] == "local"]
local

,Unnamed: 0,id,name,category,source,qasm_path,num_qubits,initial_depth,initial_two_qubit_gates,initial_two_qubit_depth,initial_total_gates,gate_density,two_qubit_ratio,created_at,optimizer_chain,original_circuit
0,0,1,efficient_su2_10_r2,efficient_su2,local,benchmarks/ai_transpile/qasm/efficient_su2_10_...,10,17,18,11,78,7.800000,0.230769,2026-03-05 20:39:31,NaN,efficient_su2_10_r2
1,1,2,efficient_su2_12,efficient_su2,local,benchmarks/ai_transpile/qasm/efficient_su2_12....,12,25,66,21,114,9.500000,0.578947,2026-03-05 20:39:31,NaN,efficient_su2_12
2,2,3,efficient_su2_12_r2,efficient_su2,local,benchmarks/ai_transpile/qasm/efficient_su2_12_...,12,19,22,13,94,7.833333,0.234043,2026-03-05 20:39:31,NaN,efficient_su2_12_r2
3,3,4,efficient_su2_16,efficient_su2,local,benchmarks/ai_transpile/qasm/efficient_su2_16....,16,33,120,29,184,11.500000,0.652174,2026-03-05 20:39:31,NaN,efficient_su2_16
4,4,5,efficient_su2_8,efficient_su2,local,benchmarks/ai_transpile/qasm/efficient_su2_8.qasm,8,27,56,21,104,13.000000,0.538462,2026-03-05 20:39:31,NaN,efficient_su2_8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,106,107,real_amplitudes_8,real_amplitudes,local,benchmarks/ai_transpile/qasm/real_amplitudes_8...,8,15,21,11,53,6.625000,0.396226,2026-03-05 20:39:34,NaN,real_amplitudes_8
107,107,108,real_amplitudes_8_r2,real_amplitudes,local,benchmarks/ai_transpile/qasm/real_amplitudes_8...,8,12,14,9,38,4.750000,0.368421,2026-03-05 20:39:34,NaN,real_amplitudes_8_r2
108,108,109,square_heisenberg_N16,square-heisenberg,local,benchmarks/ai_transpile/qasm/square-heisenberg...,16,361,288,144,1024,64.000000,0.281250,2026-03-05 20:39:34,NaN,square_heisenberg_N16
109,109,110,square_heisenberg_N4,square-heisenberg,local,benchmarks/ai_transpile/qasm/square-heisenberg...,4,121,48,48,172,43.000000,0.279070,2026-03-05 20:39:34,NaN,square_heisenberg_N4
110,110,111,square_heisenberg_N9,square-heisenberg,local,benchmarks/ai_transpile/qasm/square-heisenberg...,9,241,144,96,513,57.000000,0.280702,2026-03-05 20:39:34,NaN,square_heisenberg_N9

In [43]:
optimizers = ["qiskit_ai", "qiskit_standard", "tket", "wisq_rules", "wisq_bqskit"]
unique_paths = local["qasm_path"].unique()
len(unique_paths)

111

In [55]:
# Creates dataframe of all optimizer only combinations that have
# not been run yet

from itertools import product
import numpy as np
import json
required_df = pd.DataFrame(columns=[
    "parent_circuit_id",
    "parent_circuit",
    "original_circuit_id",
    "original_circuit",
    "original_category",
    "original_circuit_path",
    "chain_name",
    "opt_level",
    "opt_1",
    "opt_2",
    "opt_3",
    "initial_num_qubits",
    "initial_depth",
    "initial_two_qubit_gates",
    "initial_total_gates",
    "final_num_qubits",
    "final_depth",
    "final_two_qubit_gates",
    "final_total_gates",
    "total_runtime_seconds",
    "opt_chain"
])


for circuit_path in unique_paths:
    for chain_length in range(1, 4):
        for chain in product(optimizers, repeat=chain_length):
                parent_circuit_id = -1
                original_circuit_id = -1
                parent_circuit = ""
                chain_name = ""
                original_circuit = ""
                opt_level = -1
                opt_1 = "N/A"
                opt_2 = "N/A"
                opt_3 = "N/A"
                original_circuit_path = circuit_path
                initial_num_qubits = -1
                initial_depth = -1
                initial_two_qubit_gates = 0
                initial_total_gates = 0
                final_num_qubits = 0
                final_depth = 0
                final_two_qubit_gates = 0
                final_total_gates = 0
                total_runtime = 0.0

                original_circuit = circuit_path.split("/")[-1].replace(".qasm", "")

                opt_chain = original_circuit


                for opt in chain:
                     opt_chain += f"__{opt}"
                
                if (unique_df["opt_chain"] == opt_chain).any():
                     continue
                
                original_circuit_id = local[local["qasm_path"] == circuit_path]["id"].values[0]
                parent_circuit = original_circuit
                parent_circuit_id = original_circuit_id
                opt_level = len(chain)
                if chain_length > 0:
                    opt_1 = chain[0]
                if chain_length > 1: 
                    opt_2 = chain[1]
                if chain_length > 2:
                    opt_3 = chain[2]
                initial_num_qubits = local[local["qasm_path"] == circuit_path]["num_qubits"].values[0]
                initial_depth = local[local["qasm_path"] == circuit_path]["initial_depth"].values[0]
                initial_total_gates = local[local["qasm_path"] == circuit_path]["initial_total_gates"].values[0]
                initial_two_qubit_gates = local[local["qasm_path"] == circuit_path]["initial_two_qubit_gates"].values[0]
                original_category = local[local["qasm_path"] == circuit_path]["category"].values[0]


                required_df.loc[len(required_df)] = [
                    parent_circuit_id,
                    parent_circuit,
                    original_circuit_id,
                    original_circuit,
                    original_category,
                    original_circuit_path,
                    chain_name,
                    opt_level,
                    opt_1,
                    opt_2,
                    opt_3,
                    initial_num_qubits,
                    initial_depth,
                    initial_two_qubit_gates,
                    initial_total_gates,
                    final_num_qubits,
                    final_depth,
                    final_two_qubit_gates,
                    final_total_gates,
                    total_runtime,
                    opt_chain
                ]

In [58]:
required_df.to_csv("required_optimizer_only.csv", index=False)

In [64]:
# Finds current coverage of each original circuit
# Identifies number of existing and missing chains

coverage_df = pd.DataFrame(columns=[
    "original_circuit",
    "possible_chains",
    "existing_chains",
    "missing_chains"])

for circuit_path in unique_paths:
    original_circuit = circuit_path.split("/")[-1].replace(".qasm", "")
    possible_chains = 155
    existing_chains = unique_df[unique_df["original_circuit"] == original_circuit].shape[0]
    missing_chains = possible_chains - existing_chains

    coverage_df.loc[len(coverage_df)] = [
        original_circuit,
        possible_chains,
        existing_chains,
        missing_chains
    ]
coverage_df.head()

      original_circuit  possible_chains  existing_chains  missing_chains
0  efficient_su2_10_r2              155               29             126
1     efficient_su2_12              155               28             127
2  efficient_su2_12_r2              155               30             125
3     efficient_su2_16              155               28             127
4      efficient_su2_8              155               29             126

In [59]:
# Identifies best current chain for each original circuit based on two qubit gates
# then depth, then total gates

best_chain = pd.DataFrame(columns=[
    "original_circuit",
    "best_chain",
    "initial_qubits",
    "initial_depth",
    "initial_two_qubit_gates",
    "final_qubits",
    "final_depth",
    "final_two_qubit_gates"
    ])

NameError: name 'all_possible_chains' is not defined